// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EntityTypePermissionInitParameters struct {

	// An object that can hold any information about the Permission that should be persisted.  Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// The description of the Permission.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether or not the Permission is a default permission. A default permission is automatically granted to an entity of this type if no permissions are provided in a grant request.
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// The name of the Permission.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EntityTypePermissionObservation struct {

	// An object that can hold any information about the Permission that should be persisted.  Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// The description of the Permission.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The Id of the Entity Type.
	EntityTypeID *string `json:"entityTypeId,omitempty" tf:"entity_type_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether or not the Permission is a default permission. A default permission is automatically granted to an entity of this type if no permissions are provided in a grant request.
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// The name of the Permission.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EntityTypePermissionParameters struct {

	// An object that can hold any information about the Permission that should be persisted.  Must be a JSON string.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// The description of the Permission.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The Id of the Entity Type.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.EntityType
	// +kubebuilder:validation:Optional
	EntityTypeID *string `json:"entityTypeId,omitempty" tf:"entity_type_id,omitempty"`

	// Reference to a EntityType in fusionauth to populate entityTypeId.
	// +kubebuilder:validation:Optional
	EntityTypeIDRef *v2.NamespacedReference `json:"entityTypeIdRef,omitempty" tf:"-"`

	// Selector for a EntityType in fusionauth to populate entityTypeId.
	// +kubebuilder:validation:Optional
	EntityTypeIDSelector *v2.NamespacedSelector `json:"entityTypeIdSelector,omitempty" tf:"-"`

	// Whether or not the Permission is a default permission. A default permission is automatically granted to an entity of this type if no permissions are provided in a grant request.
	// +kubebuilder:validation:Optional
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// The name of the Permission.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// EntityTypePermissionSpec defines the desired state of EntityTypePermission
type EntityTypePermissionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EntityTypePermissionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EntityTypePermissionInitParameters `json:"initProvider,omitempty"`
}

// EntityTypePermissionStatus defines the observed state of EntityTypePermission.
type EntityTypePermissionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EntityTypePermissionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EntityTypePermission is the Schema for the EntityTypePermissions API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,fusionauth}
type EntityTypePermission struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EntityTypePermissionSpec   `json:"spec"`
	Status EntityTypePermissionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EntityTypePermissionList contains a list of EntityTypePermissions
type EntityTypePermissionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EntityTypePermission `json:"items"`
}

// Repository type metadata.
var (
	EntityTypePermission_Kind             = "EntityTypePermission"
	EntityTypePermission_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EntityTypePermission_Kind}.String()
	EntityTypePermission_KindAPIVersion   = EntityTypePermission_Kind + "." + CRDGroupVersion.String()
	EntityTypePermission_GroupVersionKind = CRDGroupVersion.WithKind(EntityTypePermission_Kind)
)

func init() {
	SchemeBuilder.Register(&EntityTypePermission{}, &EntityTypePermissionList{})
}
