// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type LambdaInitParameters struct {

	// The lambda function body, a JavaScript function.
	// The lambda function body, a JavaScript function.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// Whether or not debug event logging is enabled for this Lambda.
	// Whether or not debug event logging is enabled for this Lambda.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// Whether or not this Lambda is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The JavaScript execution engine for the lambda.
	// The JavaScript execution engine for the lambda.
	EngineType *string `json:"engineType,omitempty" tf:"engine_type,omitempty"`

	// The Id to use for the new lambda. If not specified a secure random UUID will be generated.
	// The Id to use for the new lambda. If not specified a secure random UUID will be generated.
	LambdaID *string `json:"lambdaId,omitempty" tf:"lambda_id,omitempty"`

	// The name of the lambda.
	// The name of the lambda.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The lambda type. The possible values are:
	// The lambda type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LambdaObservation struct {

	// The lambda function body, a JavaScript function.
	// The lambda function body, a JavaScript function.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// Whether or not debug event logging is enabled for this Lambda.
	// Whether or not debug event logging is enabled for this Lambda.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// Whether or not this Lambda is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The JavaScript execution engine for the lambda.
	// The JavaScript execution engine for the lambda.
	EngineType *string `json:"engineType,omitempty" tf:"engine_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Id to use for the new lambda. If not specified a secure random UUID will be generated.
	// The Id to use for the new lambda. If not specified a secure random UUID will be generated.
	LambdaID *string `json:"lambdaId,omitempty" tf:"lambda_id,omitempty"`

	// The name of the lambda.
	// The name of the lambda.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The lambda type. The possible values are:
	// The lambda type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LambdaParameters struct {

	// The lambda function body, a JavaScript function.
	// The lambda function body, a JavaScript function.
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// Whether or not debug event logging is enabled for this Lambda.
	// Whether or not debug event logging is enabled for this Lambda.
	// +kubebuilder:validation:Optional
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// Whether or not this Lambda is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The JavaScript execution engine for the lambda.
	// The JavaScript execution engine for the lambda.
	// +kubebuilder:validation:Optional
	EngineType *string `json:"engineType,omitempty" tf:"engine_type,omitempty"`

	// The Id to use for the new lambda. If not specified a secure random UUID will be generated.
	// The Id to use for the new lambda. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	LambdaID *string `json:"lambdaId,omitempty" tf:"lambda_id,omitempty"`

	// The name of the lambda.
	// The name of the lambda.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The lambda type. The possible values are:
	// The lambda type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// LambdaSpec defines the desired state of Lambda
type LambdaSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LambdaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LambdaInitParameters `json:"initProvider,omitempty"`
}

// LambdaStatus defines the observed state of Lambda.
type LambdaStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LambdaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Lambda is the Schema for the Lambdas API. Lambda Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,fusionauth}
type Lambda struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.body) || (has(self.initProvider) && has(self.initProvider.body))",message="spec.forProvider.body is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   LambdaSpec   `json:"spec"`
	Status LambdaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LambdaList contains a list of Lambdas
type LambdaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Lambda `json:"items"`
}

// Repository type metadata.
var (
	Lambda_Kind             = "Lambda"
	Lambda_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Lambda_Kind}.String()
	Lambda_KindAPIVersion   = Lambda_Kind + "." + CRDGroupVersion.String()
	Lambda_GroupVersionKind = CRDGroupVersion.WithKind(Lambda_Kind)
)

func init() {
	SchemeBuilder.Register(&Lambda{}, &LambdaList{})
}
