// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IdentitiesInitParameters struct {
}

type IdentitiesObservation struct {

	// The display value for the identity. Only used for username type identities. If the unique username feature is not enabled, this value will be the same as user.identities[x].value. Otherwise, it will be the username the User has chosen. For primary username identities, this will be the same value as user.username.
	// The display value for the identity. Only used for username type identities. If the unique username feature is not enabled, this value will be the same as user.identities[x].value. Otherwise, it will be the username the User has chosen. For primary username identities, this will be the same value as user.username .
	DisplayValue *string `json:"displayValue,omitempty" tf:"display_value,omitempty"`

	// The instant when the identity was created.
	// The instant when the identity was created.
	InsertInstant *int64 `json:"insertInstant,omitempty" tf:"insert_instant,omitempty"`

	// The instant when the identity was last used to log in. If a User has multiple identity types (username, email, and phoneNumber), then this value will represent the specific identity they last used to log in. This contrasts with user.lastLoginInstant, which represents the last time any of the User’s identities was used to log in.
	// The instant when the identity was last used to log in. If a User has multiple identity types (username, email, and phoneNumber), then this value will represent the specific identity they last used to log in. This contrasts with user.lastLoginInstant, which represents the last time any of the User’s identities was used to log in.
	LastLoginInstant *int64 `json:"lastLoginInstant,omitempty" tf:"last_login_instant,omitempty"`

	// The instant when the identity was last updated.
	// The instant when the identity was last updated.
	LastUpdateInstant *int64 `json:"lastUpdateInstant,omitempty" tf:"last_update_instant,omitempty"`

	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	ModerationStatus *string `json:"moderationStatus,omitempty" tf:"moderation_status,omitempty"`

	// The identity type that the verification Id is for. This identity type, along with verificationIds[x].value , matches exactly one identity via user.identities[x].type.
	// The identity type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The identity value that the verification Id is for. This identity value, along with verificationIds[x].type , matches exactly one identity via user.identities[x].value.
	// The value represented by the identity.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// Whether verification was actually performed on the identity by FusionAuth.
	// Whether verification was actually performed on the identity by FusionAuth.
	Verified *bool `json:"verified,omitempty" tf:"verified,omitempty"`

	// The instant when verification was performed on the identity.
	// The instant when verification was performed on the identity.
	VerifiedInstant *int64 `json:"verifiedInstant,omitempty" tf:"verified_instant,omitempty"`

	// The reason the User’s identity was verified or not verified.
	// The reason the User’s identity was verified or not verified.
	VerifiedReason *string `json:"verifiedReason,omitempty" tf:"verified_reason,omitempty"`
}

type IdentitiesParameters struct {
}

type TwoFactorMethodsInitParameters struct {

	// The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1.
	// The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1.
	AuthenticatorAlgorithm *string `json:"authenticatorAlgorithm,omitempty" tf:"authenticator_algorithm,omitempty"`

	// The length of code generated by the TOTP. With the current implementation, this will always be 6.
	// The length of code generated by the TOTP. With the current implementation, this will always be 6.
	AuthenticatorCodeLength *int64 `json:"authenticatorCodeLength,omitempty" tf:"authenticator_code_length,omitempty"`

	// The time-step size in seconds. With the current implementation, this will always be 30.
	// The time-step size in seconds. With the current implementation, this will always be 30.
	AuthenticatorTimeStep *int64 `json:"authenticatorTimeStep,omitempty" tf:"authenticator_time_step,omitempty"`

	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// The value of the email address for this method. Only present if user.twoFactor.methods[x].method is email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The type of this method. There will also be an object with the same value containing additional information about this method.
	// The type of this method. There will also be an object with the same value containing additional information about this method.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// The value of the mobile phone for this method. Only present if user.twoFactor.methods[x].method is sms.
	MobilePhone *string `json:"mobilePhone,omitempty" tf:"mobile_phone,omitempty"`

	// A user-friendly name for this two-factor method, for example "Work authenticator".
	// A user-friendly name for this two-factor method, for example "Work authenticator".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A base64 encoded secret
	// A base64 encoded secret
	SecretSecretRef *v2.LocalSecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`
}

type TwoFactorMethodsObservation struct {

	// The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1.
	// The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1.
	AuthenticatorAlgorithm *string `json:"authenticatorAlgorithm,omitempty" tf:"authenticator_algorithm,omitempty"`

	// The length of code generated by the TOTP. With the current implementation, this will always be 6.
	// The length of code generated by the TOTP. With the current implementation, this will always be 6.
	AuthenticatorCodeLength *int64 `json:"authenticatorCodeLength,omitempty" tf:"authenticator_code_length,omitempty"`

	// The time-step size in seconds. With the current implementation, this will always be 30.
	// The time-step size in seconds. With the current implementation, this will always be 30.
	AuthenticatorTimeStep *int64 `json:"authenticatorTimeStep,omitempty" tf:"authenticator_time_step,omitempty"`

	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// The value of the email address for this method. Only present if user.twoFactor.methods[x].method is email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The type of this method. There will also be an object with the same value containing additional information about this method.
	// The type of this method. There will also be an object with the same value containing additional information about this method.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// The value of the mobile phone for this method. Only present if user.twoFactor.methods[x].method is sms.
	MobilePhone *string `json:"mobilePhone,omitempty" tf:"mobile_phone,omitempty"`

	// A user-friendly name for this two-factor method, for example "Work authenticator".
	// A user-friendly name for this two-factor method, for example "Work authenticator".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The unique Id of the method.
	TwoFactorMethodID *string `json:"twoFactorMethodId,omitempty" tf:"two_factor_method_id,omitempty"`
}

type TwoFactorMethodsParameters struct {

	// The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1.
	// The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1.
	// +kubebuilder:validation:Optional
	AuthenticatorAlgorithm *string `json:"authenticatorAlgorithm,omitempty" tf:"authenticator_algorithm,omitempty"`

	// The length of code generated by the TOTP. With the current implementation, this will always be 6.
	// The length of code generated by the TOTP. With the current implementation, this will always be 6.
	// +kubebuilder:validation:Optional
	AuthenticatorCodeLength *int64 `json:"authenticatorCodeLength,omitempty" tf:"authenticator_code_length,omitempty"`

	// The time-step size in seconds. With the current implementation, this will always be 30.
	// The time-step size in seconds. With the current implementation, this will always be 30.
	// +kubebuilder:validation:Optional
	AuthenticatorTimeStep *int64 `json:"authenticatorTimeStep,omitempty" tf:"authenticator_time_step,omitempty"`

	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// The value of the email address for this method. Only present if user.twoFactor.methods[x].method is email.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The type of this method. There will also be an object with the same value containing additional information about this method.
	// The type of this method. There will also be an object with the same value containing additional information about this method.
	// +kubebuilder:validation:Optional
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// The value of the mobile phone for this method. Only present if user.twoFactor.methods[x].method is sms.
	// +kubebuilder:validation:Optional
	MobilePhone *string `json:"mobilePhone,omitempty" tf:"mobile_phone,omitempty"`

	// A user-friendly name for this two-factor method, for example "Work authenticator".
	// A user-friendly name for this two-factor method, for example "Work authenticator".
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A base64 encoded secret
	// A base64 encoded secret
	// +kubebuilder:validation:Optional
	SecretSecretRef *v2.LocalSecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`
}

type UserInitParameters struct {

	// An optional Application Id. When this value is provided, it will be used to resolve an application specific email template if you have configured transactional emails such as setup password, email verification and others.
	// An optional Application Id. When this value is provided, it will be used to resolve an application specific email template if you have configured transactional emails such as setup password, email verification and others.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// An ISO-8601 formatted date of the User’s birthdate such as YYYY-MM-DD.
	// An ISO-8601 formatted date of the User’s birthdate such as YYYY-MM-DD.
	BirthDate *string `json:"birthDate,omitempty" tf:"birth_date,omitempty"`

	// A JSON string that can hold any information about a User that should be persisted. Must be a JSON serialised string.
	// An object that can hold any information about a User that should be persisted. Must be a JSON encoded string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// A tenant has the option to configure one or more email domains to be blocked in order to restrict email domains during user create or update. Setting this property equal to true will override the tenant configuration. See registration_configuration.blocked_domains in the Tenant resource.
	// A tenant has the option to configure one or more email domains to be blocked in order to restrict email domains during user create or update.
	DisableDomainBlock *bool `json:"disableDomainBlock,omitempty" tf:"disable_domain_block,omitempty"`

	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The method for encrypting the User’s password.
	// The method for encrypting the User’s password.
	EncryptionScheme *string `json:"encryptionScheme,omitempty" tf:"encryption_scheme,omitempty"`

	// The expiration instant of the User’s account. An expired user is not permitted to login.
	// The expiration instant of the User’s account. An expired user is not permitted to login.
	Expiry *int64 `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// The factor used by the password encryption scheme. If not provided, the PasswordEncryptor provides a default value. Generally this will be used as an iteration count to generate the hash. The actual use of this value is up to the PasswordEncryptor implementation.
	Factor *int64 `json:"factor,omitempty" tf:"factor,omitempty"`

	// The first name of the User.
	// The first name of the User.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// The User’s full name as a separate field that is not calculated from firstName and lastName.
	// The User’s full name as a separate field that is not calculated from firstName and lastName.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// The URL that points to an image file that is the User’s profile image.
	// The URL that points to an image file that is the User’s profile image.
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// The User’s last name.
	// The User’s last name.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// The User’s middle name.
	// The User’s middle name.
	MiddleName *string `json:"middleName,omitempty" tf:"middle_name,omitempty"`

	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	MobilePhone *string `json:"mobilePhone,omitempty" tf:"mobile_phone,omitempty"`

	// The email address of the user’s parent or guardian. This field is used to allow a child user to identify their parent so FusionAuth can make a request to the parent to confirm the parent relationship.
	// The email address of the user’s parent or guardian. This field is used to allow a child user to identify their parent so FusionAuth can make a request to the parent to confirm the parent relationship.
	ParentEmail *string `json:"parentEmail,omitempty" tf:"parent_email,omitempty"`

	// Indicates that the User’s password needs to be changed during their next login attempt.
	// Indicates that the User’s password needs to be changed during their next login attempt.
	PasswordChangeRequired *bool `json:"passwordChangeRequired,omitempty" tf:"password_change_required,omitempty"`

	// The User’s plaintext password. This password will be hashed and the provided value will never be stored and cannot be retrieved.
	// The User's plaintext password. This password will be hashed and the provided value will never be stored and cannot be retrieved.
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The phone number of the User. The phone number is stored and returned in E.164 canonical format, however a phone number is considered unique regardless of the format. 303-555-1212 is considered equal to +13035551212 so either version of this phone number can be used whenever providing it as input to an API. If phone_number is not provided, then email or username will be required.
	// The phone number of the User. The phone number is stored and returned in E.164 canonical format, however a phone number is considered unique regardless of the format. 303-555-1212 is considered equal to +13035551212 so either version of this phone number can be used whenever providing it as input to an API. If phone_number is not provided, then email or username will be required.
	PhoneNumber *string `json:"phoneNumber,omitempty" tf:"phone_number,omitempty"`

	// An array of locale strings that give, in order, the User’s preferred languages. These are important for email templates and other localizable text.
	// An array of locale strings that give, in order, the User’s preferred languages. These are important for email templates and other localizable text.
	// +listType=set
	PreferredLanguages []*string `json:"preferredLanguages,omitempty" tf:"preferred_languages,omitempty"`

	// Indicates to FusionAuth to send the User an email asking them to set their password. The Email Template that is used is configured in the System Configuration setting for Set Password Email Template. Use send_set_password_identity_type instead.
	// Indicates to FusionAuth to send the User an email asking them to set their password. The Email Template that is used is configured in the System Configuration setting for Set Password Email Template.
	SendSetPasswordEmail *bool `json:"sendSetPasswordEmail,omitempty" tf:"send_set_password_email,omitempty"`

	// If set, FusionAuth will send the User a message asking them to set their password. When you set this value to anything but doNotSend, any provided password field is ignored. The possible values are doNotSend, email, and phone.
	// If set, FusionAuth will send the User a message asking them to set their password. When you set this value to anything but `doNotSend`, any provided password field is ignored. The possible values are `doNotSend`, `email`, and `phone`.
	SendSetPasswordIdentityType *string `json:"sendSetPasswordIdentityType,omitempty" tf:"send_set_password_identity_type,omitempty"`

	// Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.
	// Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.
	SkipVerification *bool `json:"skipVerification,omitempty" tf:"skip_verification,omitempty"`

	// The unique Id of the tenant used to scope this API request.
	// The unique Id of the tenant used to scope this API request.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`

	// The User’s preferred timezone. The string must be in an IANA time zone format.
	// The User’s preferred timezone. The string must be in an IANA time zone format. For example:
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	TwoFactorMethods []TwoFactorMethodsInitParameters `json:"twoFactorMethods,omitempty" tf:"two_factor_methods,omitempty"`

	// The Id to use for the new User. If not specified a secure random UUID will be generated..
	// The Id to use for the new User. If not specified a secure random UUID will be generated.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The username of the User. The username is stored and returned as a case sensitive value, however a username is considered unique regardless of the case. bob is considered equal to BoB so either version of this username can be used whenever providing it as input to an API.
	// The username of the User. The username is stored and returned as a case sensitive value, however a username is considered unique regardless of the case. bob is considered equal to BoB so either version of this username can be used whenever providing it as input to an API.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	UsernameStatus *string `json:"usernameStatus,omitempty" tf:"username_status,omitempty"`

	// The list of all verifications that exist for a user. This includes the email and phone identities that a user may have. The values from emailVerificationId and emailVerificationOneTimeCode are legacy fields and will also be present in this list.
	// The list of all verifications that exist for a user. This includes the email and phone identities that a user may have. The values from emailVerificationId and emailVerificationOneTimeCode are legacy fields and will also be present in this list.
	VerificationIds []VerificationIdsInitParameters `json:"verificationIds,omitempty" tf:"verification_ids,omitempty"`
}

type UserObservation struct {

	// An optional Application Id. When this value is provided, it will be used to resolve an application specific email template if you have configured transactional emails such as setup password, email verification and others.
	// An optional Application Id. When this value is provided, it will be used to resolve an application specific email template if you have configured transactional emails such as setup password, email verification and others.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// An ISO-8601 formatted date of the User’s birthdate such as YYYY-MM-DD.
	// An ISO-8601 formatted date of the User’s birthdate such as YYYY-MM-DD.
	BirthDate *string `json:"birthDate,omitempty" tf:"birth_date,omitempty"`

	// A JSON string that can hold any information about a User that should be persisted. Must be a JSON serialised string.
	// An object that can hold any information about a User that should be persisted. Must be a JSON encoded string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// A tenant has the option to configure one or more email domains to be blocked in order to restrict email domains during user create or update. Setting this property equal to true will override the tenant configuration. See registration_configuration.blocked_domains in the Tenant resource.
	// A tenant has the option to configure one or more email domains to be blocked in order to restrict email domains during user create or update.
	DisableDomainBlock *bool `json:"disableDomainBlock,omitempty" tf:"disable_domain_block,omitempty"`

	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The method for encrypting the User’s password.
	// The method for encrypting the User’s password.
	EncryptionScheme *string `json:"encryptionScheme,omitempty" tf:"encryption_scheme,omitempty"`

	// The expiration instant of the User’s account. An expired user is not permitted to login.
	// The expiration instant of the User’s account. An expired user is not permitted to login.
	Expiry *int64 `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// The factor used by the password encryption scheme. If not provided, the PasswordEncryptor provides a default value. Generally this will be used as an iteration count to generate the hash. The actual use of this value is up to the PasswordEncryptor implementation.
	Factor *int64 `json:"factor,omitempty" tf:"factor,omitempty"`

	// The first name of the User.
	// The first name of the User.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// The User’s full name as a separate field that is not calculated from firstName and lastName.
	// The User’s full name as a separate field that is not calculated from firstName and lastName.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The list of identities that exist for a User.
	// The list of identities that exist for a User.
	Identities []IdentitiesObservation `json:"identities,omitempty" tf:"identities,omitempty"`

	// The URL that points to an image file that is the User’s profile image.
	// The URL that points to an image file that is the User’s profile image.
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// The User’s last name.
	// The User’s last name.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// The User’s middle name.
	// The User’s middle name.
	MiddleName *string `json:"middleName,omitempty" tf:"middle_name,omitempty"`

	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	MobilePhone *string `json:"mobilePhone,omitempty" tf:"mobile_phone,omitempty"`

	// The email address of the user’s parent or guardian. This field is used to allow a child user to identify their parent so FusionAuth can make a request to the parent to confirm the parent relationship.
	// The email address of the user’s parent or guardian. This field is used to allow a child user to identify their parent so FusionAuth can make a request to the parent to confirm the parent relationship.
	ParentEmail *string `json:"parentEmail,omitempty" tf:"parent_email,omitempty"`

	// Indicates that the User’s password needs to be changed during their next login attempt.
	// Indicates that the User’s password needs to be changed during their next login attempt.
	PasswordChangeRequired *bool `json:"passwordChangeRequired,omitempty" tf:"password_change_required,omitempty"`

	// The phone number of the User. The phone number is stored and returned in E.164 canonical format, however a phone number is considered unique regardless of the format. 303-555-1212 is considered equal to +13035551212 so either version of this phone number can be used whenever providing it as input to an API. If phone_number is not provided, then email or username will be required.
	// The phone number of the User. The phone number is stored and returned in E.164 canonical format, however a phone number is considered unique regardless of the format. 303-555-1212 is considered equal to +13035551212 so either version of this phone number can be used whenever providing it as input to an API. If phone_number is not provided, then email or username will be required.
	PhoneNumber *string `json:"phoneNumber,omitempty" tf:"phone_number,omitempty"`

	// An array of locale strings that give, in order, the User’s preferred languages. These are important for email templates and other localizable text.
	// An array of locale strings that give, in order, the User’s preferred languages. These are important for email templates and other localizable text.
	// +listType=set
	PreferredLanguages []*string `json:"preferredLanguages,omitempty" tf:"preferred_languages,omitempty"`

	// Indicates to FusionAuth to send the User an email asking them to set their password. The Email Template that is used is configured in the System Configuration setting for Set Password Email Template. Use send_set_password_identity_type instead.
	// Indicates to FusionAuth to send the User an email asking them to set their password. The Email Template that is used is configured in the System Configuration setting for Set Password Email Template.
	SendSetPasswordEmail *bool `json:"sendSetPasswordEmail,omitempty" tf:"send_set_password_email,omitempty"`

	// If set, FusionAuth will send the User a message asking them to set their password. When you set this value to anything but doNotSend, any provided password field is ignored. The possible values are doNotSend, email, and phone.
	// If set, FusionAuth will send the User a message asking them to set their password. When you set this value to anything but `doNotSend`, any provided password field is ignored. The possible values are `doNotSend`, `email`, and `phone`.
	SendSetPasswordIdentityType *string `json:"sendSetPasswordIdentityType,omitempty" tf:"send_set_password_identity_type,omitempty"`

	// Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.
	// Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.
	SkipVerification *bool `json:"skipVerification,omitempty" tf:"skip_verification,omitempty"`

	// The unique Id of the tenant used to scope this API request.
	// The unique Id of the tenant used to scope this API request.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// The User’s preferred timezone. The string must be in an IANA time zone format.
	// The User’s preferred timezone. The string must be in an IANA time zone format. For example:
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	TwoFactorMethods []TwoFactorMethodsObservation `json:"twoFactorMethods,omitempty" tf:"two_factor_methods,omitempty"`

	// The Id to use for the new User. If not specified a secure random UUID will be generated..
	// The Id to use for the new User. If not specified a secure random UUID will be generated.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The username of the User. The username is stored and returned as a case sensitive value, however a username is considered unique regardless of the case. bob is considered equal to BoB so either version of this username can be used whenever providing it as input to an API.
	// The username of the User. The username is stored and returned as a case sensitive value, however a username is considered unique regardless of the case. bob is considered equal to BoB so either version of this username can be used whenever providing it as input to an API.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	UsernameStatus *string `json:"usernameStatus,omitempty" tf:"username_status,omitempty"`

	// The list of all verifications that exist for a user. This includes the email and phone identities that a user may have. The values from emailVerificationId and emailVerificationOneTimeCode are legacy fields and will also be present in this list.
	// The list of all verifications that exist for a user. This includes the email and phone identities that a user may have. The values from emailVerificationId and emailVerificationOneTimeCode are legacy fields and will also be present in this list.
	VerificationIds []VerificationIdsObservation `json:"verificationIds,omitempty" tf:"verification_ids,omitempty"`
}

type UserParameters struct {

	// An optional Application Id. When this value is provided, it will be used to resolve an application specific email template if you have configured transactional emails such as setup password, email verification and others.
	// An optional Application Id. When this value is provided, it will be used to resolve an application specific email template if you have configured transactional emails such as setup password, email verification and others.
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// An ISO-8601 formatted date of the User’s birthdate such as YYYY-MM-DD.
	// An ISO-8601 formatted date of the User’s birthdate such as YYYY-MM-DD.
	// +kubebuilder:validation:Optional
	BirthDate *string `json:"birthDate,omitempty" tf:"birth_date,omitempty"`

	// A JSON string that can hold any information about a User that should be persisted. Must be a JSON serialised string.
	// An object that can hold any information about a User that should be persisted. Must be a JSON encoded string.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// A tenant has the option to configure one or more email domains to be blocked in order to restrict email domains during user create or update. Setting this property equal to true will override the tenant configuration. See registration_configuration.blocked_domains in the Tenant resource.
	// A tenant has the option to configure one or more email domains to be blocked in order to restrict email domains during user create or update.
	// +kubebuilder:validation:Optional
	DisableDomainBlock *bool `json:"disableDomainBlock,omitempty" tf:"disable_domain_block,omitempty"`

	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// The User’s email address. An email address is a unique in FusionAuth and stored in lower case.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The method for encrypting the User’s password.
	// The method for encrypting the User’s password.
	// +kubebuilder:validation:Optional
	EncryptionScheme *string `json:"encryptionScheme,omitempty" tf:"encryption_scheme,omitempty"`

	// The expiration instant of the User’s account. An expired user is not permitted to login.
	// The expiration instant of the User’s account. An expired user is not permitted to login.
	// +kubebuilder:validation:Optional
	Expiry *int64 `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// The factor used by the password encryption scheme. If not provided, the PasswordEncryptor provides a default value. Generally this will be used as an iteration count to generate the hash. The actual use of this value is up to the PasswordEncryptor implementation.
	// +kubebuilder:validation:Optional
	Factor *int64 `json:"factor,omitempty" tf:"factor,omitempty"`

	// The first name of the User.
	// The first name of the User.
	// +kubebuilder:validation:Optional
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// The User’s full name as a separate field that is not calculated from firstName and lastName.
	// The User’s full name as a separate field that is not calculated from firstName and lastName.
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// The URL that points to an image file that is the User’s profile image.
	// The URL that points to an image file that is the User’s profile image.
	// +kubebuilder:validation:Optional
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// The User’s last name.
	// The User’s last name.
	// +kubebuilder:validation:Optional
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// The User’s middle name.
	// The User’s middle name.
	// +kubebuilder:validation:Optional
	MiddleName *string `json:"middleName,omitempty" tf:"middle_name,omitempty"`

	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// The User’s mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.
	// +kubebuilder:validation:Optional
	MobilePhone *string `json:"mobilePhone,omitempty" tf:"mobile_phone,omitempty"`

	// The email address of the user’s parent or guardian. This field is used to allow a child user to identify their parent so FusionAuth can make a request to the parent to confirm the parent relationship.
	// The email address of the user’s parent or guardian. This field is used to allow a child user to identify their parent so FusionAuth can make a request to the parent to confirm the parent relationship.
	// +kubebuilder:validation:Optional
	ParentEmail *string `json:"parentEmail,omitempty" tf:"parent_email,omitempty"`

	// Indicates that the User’s password needs to be changed during their next login attempt.
	// Indicates that the User’s password needs to be changed during their next login attempt.
	// +kubebuilder:validation:Optional
	PasswordChangeRequired *bool `json:"passwordChangeRequired,omitempty" tf:"password_change_required,omitempty"`

	// The User’s plaintext password. This password will be hashed and the provided value will never be stored and cannot be retrieved.
	// The User's plaintext password. This password will be hashed and the provided value will never be stored and cannot be retrieved.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The phone number of the User. The phone number is stored and returned in E.164 canonical format, however a phone number is considered unique regardless of the format. 303-555-1212 is considered equal to +13035551212 so either version of this phone number can be used whenever providing it as input to an API. If phone_number is not provided, then email or username will be required.
	// The phone number of the User. The phone number is stored and returned in E.164 canonical format, however a phone number is considered unique regardless of the format. 303-555-1212 is considered equal to +13035551212 so either version of this phone number can be used whenever providing it as input to an API. If phone_number is not provided, then email or username will be required.
	// +kubebuilder:validation:Optional
	PhoneNumber *string `json:"phoneNumber,omitempty" tf:"phone_number,omitempty"`

	// An array of locale strings that give, in order, the User’s preferred languages. These are important for email templates and other localizable text.
	// An array of locale strings that give, in order, the User’s preferred languages. These are important for email templates and other localizable text.
	// +kubebuilder:validation:Optional
	// +listType=set
	PreferredLanguages []*string `json:"preferredLanguages,omitempty" tf:"preferred_languages,omitempty"`

	// Indicates to FusionAuth to send the User an email asking them to set their password. The Email Template that is used is configured in the System Configuration setting for Set Password Email Template. Use send_set_password_identity_type instead.
	// Indicates to FusionAuth to send the User an email asking them to set their password. The Email Template that is used is configured in the System Configuration setting for Set Password Email Template.
	// +kubebuilder:validation:Optional
	SendSetPasswordEmail *bool `json:"sendSetPasswordEmail,omitempty" tf:"send_set_password_email,omitempty"`

	// If set, FusionAuth will send the User a message asking them to set their password. When you set this value to anything but doNotSend, any provided password field is ignored. The possible values are doNotSend, email, and phone.
	// If set, FusionAuth will send the User a message asking them to set their password. When you set this value to anything but `doNotSend`, any provided password field is ignored. The possible values are `doNotSend`, `email`, and `phone`.
	// +kubebuilder:validation:Optional
	SendSetPasswordIdentityType *string `json:"sendSetPasswordIdentityType,omitempty" tf:"send_set_password_identity_type,omitempty"`

	// Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.
	// Indicates to FusionAuth that it should skip email verification even if it is enabled. This is useful for creating admin or internal User accounts.
	// +kubebuilder:validation:Optional
	SkipVerification *bool `json:"skipVerification,omitempty" tf:"skip_verification,omitempty"`

	// The unique Id of the tenant used to scope this API request.
	// The unique Id of the tenant used to scope this API request.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`

	// The User’s preferred timezone. The string must be in an IANA time zone format.
	// The User’s preferred timezone. The string must be in an IANA time zone format. For example:
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// +kubebuilder:validation:Optional
	TwoFactorMethods []TwoFactorMethodsParameters `json:"twoFactorMethods,omitempty" tf:"two_factor_methods,omitempty"`

	// The Id to use for the new User. If not specified a secure random UUID will be generated..
	// The Id to use for the new User. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The username of the User. The username is stored and returned as a case sensitive value, however a username is considered unique regardless of the case. bob is considered equal to BoB so either version of this username can be used whenever providing it as input to an API.
	// The username of the User. The username is stored and returned as a case sensitive value, however a username is considered unique regardless of the case. bob is considered equal to BoB so either version of this username can be used whenever providing it as input to an API.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	// The current status of the username. This is used if you are moderating usernames via CleanSpeak.
	// +kubebuilder:validation:Optional
	UsernameStatus *string `json:"usernameStatus,omitempty" tf:"username_status,omitempty"`

	// The list of all verifications that exist for a user. This includes the email and phone identities that a user may have. The values from emailVerificationId and emailVerificationOneTimeCode are legacy fields and will also be present in this list.
	// The list of all verifications that exist for a user. This includes the email and phone identities that a user may have. The values from emailVerificationId and emailVerificationOneTimeCode are legacy fields and will also be present in this list.
	// +kubebuilder:validation:Optional
	VerificationIds []VerificationIdsParameters `json:"verificationIds,omitempty" tf:"verification_ids,omitempty"`
}

type VerificationIdsInitParameters struct {

	// A verification Id.
	// A verification Id.
	VerificationID *string `json:"verificationId,omitempty" tf:"verification_id,omitempty"`
}

type VerificationIdsObservation struct {

	// A one time code that will be paired with the verificationIds[x].id.
	// A one time code that will be paired with the verificationIds[x].id .
	OneTimeCode *string `json:"oneTimeCode,omitempty" tf:"one_time_code,omitempty"`

	// The identity type that the verification Id is for. This identity type, along with verificationIds[x].value , matches exactly one identity via user.identities[x].type.
	// The identity type that the verification Id is for. This identity type, along with verificationIds[x].value , matches exactly one identity via user.identities[x].type .
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The identity value that the verification Id is for. This identity value, along with verificationIds[x].type , matches exactly one identity via user.identities[x].value.
	// The identity value that the verification Id is for. This identity value, along with verificationIds[x].type , matches exactly one identity via user.identities[x].value .
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// A verification Id.
	// A verification Id.
	VerificationID *string `json:"verificationId,omitempty" tf:"verification_id,omitempty"`
}

type VerificationIdsParameters struct {

	// A verification Id.
	// A verification Id.
	// +kubebuilder:validation:Optional
	VerificationID *string `json:"verificationId,omitempty" tf:"verification_id,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. User Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,fusionauth}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserSpec   `json:"spec"`
	Status            UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
