apiVersion: fusionauth.crossplane.io/v1alpha1
kind: UserAction
metadata:
  annotations:
    meta.upbound.io/example-id: fusionauth/v1alpha1/useraction
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Lock user
    preventLogin: true
    temporal: true
