//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConfigurationsInitParameters) DeepCopyInto(out *ApplicationConfigurationsInitParameters) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.ApplicationIDRef != nil {
		in, out := &in.ApplicationIDRef, &out.ApplicationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationIDSelector != nil {
		in, out := &in.ApplicationIDSelector, &out.ApplicationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConfigurationsInitParameters.
func (in *ApplicationConfigurationsInitParameters) DeepCopy() *ApplicationConfigurationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationConfigurationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConfigurationsObservation) DeepCopyInto(out *ApplicationConfigurationsObservation) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConfigurationsObservation.
func (in *ApplicationConfigurationsObservation) DeepCopy() *ApplicationConfigurationsObservation {
	if in == nil {
		return nil
	}
	out := new(ApplicationConfigurationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConfigurationsParameters) DeepCopyInto(out *ApplicationConfigurationsParameters) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.ApplicationIDRef != nil {
		in, out := &in.ApplicationIDRef, &out.ApplicationIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationIDSelector != nil {
		in, out := &in.ApplicationIDSelector, &out.ApplicationIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConfigurationsParameters.
func (in *ApplicationConfigurationsParameters) DeepCopy() *ApplicationConfigurationsParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationConfigurationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderTypeConfigurationsInitParameters) DeepCopyInto(out *IdentityProviderTypeConfigurationsInitParameters) {
	*out = *in
	if in.DefaultAttributeMappings != nil {
		in, out := &in.DefaultAttributeMappings, &out.DefaultAttributeMappings
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LinkingStrategy != nil {
		in, out := &in.LinkingStrategy, &out.LinkingStrategy
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderTypeConfigurationsInitParameters.
func (in *IdentityProviderTypeConfigurationsInitParameters) DeepCopy() *IdentityProviderTypeConfigurationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderTypeConfigurationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderTypeConfigurationsObservation) DeepCopyInto(out *IdentityProviderTypeConfigurationsObservation) {
	*out = *in
	if in.DefaultAttributeMappings != nil {
		in, out := &in.DefaultAttributeMappings, &out.DefaultAttributeMappings
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LinkingStrategy != nil {
		in, out := &in.LinkingStrategy, &out.LinkingStrategy
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderTypeConfigurationsObservation.
func (in *IdentityProviderTypeConfigurationsObservation) DeepCopy() *IdentityProviderTypeConfigurationsObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderTypeConfigurationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderTypeConfigurationsParameters) DeepCopyInto(out *IdentityProviderTypeConfigurationsParameters) {
	*out = *in
	if in.DefaultAttributeMappings != nil {
		in, out := &in.DefaultAttributeMappings, &out.DefaultAttributeMappings
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LinkingStrategy != nil {
		in, out := &in.LinkingStrategy, &out.LinkingStrategy
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderTypeConfigurationsParameters.
func (in *IdentityProviderTypeConfigurationsParameters) DeepCopy() *IdentityProviderTypeConfigurationsParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderTypeConfigurationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfiguration) DeepCopyInto(out *ManagerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfiguration.
func (in *ManagerConfiguration) DeepCopy() *ManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfigurationInitParameters) DeepCopyInto(out *ManagerConfigurationInitParameters) {
	*out = *in
	if in.ApplicationConfigurations != nil {
		in, out := &in.ApplicationConfigurations, &out.ApplicationConfigurations
		*out = make([]ApplicationConfigurationsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttributeFormID != nil {
		in, out := &in.AttributeFormID, &out.AttributeFormID
		*out = new(string)
		**out = **in
	}
	if in.AttributeFormIDRef != nil {
		in, out := &in.AttributeFormIDRef, &out.AttributeFormIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AttributeFormIDSelector != nil {
		in, out := &in.AttributeFormIDSelector, &out.AttributeFormIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.BrandName != nil {
		in, out := &in.BrandName, &out.BrandName
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderTypeConfigurations != nil {
		in, out := &in.IdentityProviderTypeConfigurations, &out.IdentityProviderTypeConfigurations
		*out = make([]IdentityProviderTypeConfigurationsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfigurationInitParameters.
func (in *ManagerConfigurationInitParameters) DeepCopy() *ManagerConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagerConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfigurationList) DeepCopyInto(out *ManagerConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagerConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfigurationList.
func (in *ManagerConfigurationList) DeepCopy() *ManagerConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ManagerConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagerConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfigurationObservation) DeepCopyInto(out *ManagerConfigurationObservation) {
	*out = *in
	if in.ApplicationConfigurations != nil {
		in, out := &in.ApplicationConfigurations, &out.ApplicationConfigurations
		*out = make([]ApplicationConfigurationsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttributeFormID != nil {
		in, out := &in.AttributeFormID, &out.AttributeFormID
		*out = new(string)
		**out = **in
	}
	if in.BrandName != nil {
		in, out := &in.BrandName, &out.BrandName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderTypeConfigurations != nil {
		in, out := &in.IdentityProviderTypeConfigurations, &out.IdentityProviderTypeConfigurations
		*out = make([]IdentityProviderTypeConfigurationsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfigurationObservation.
func (in *ManagerConfigurationObservation) DeepCopy() *ManagerConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ManagerConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfigurationParameters) DeepCopyInto(out *ManagerConfigurationParameters) {
	*out = *in
	if in.ApplicationConfigurations != nil {
		in, out := &in.ApplicationConfigurations, &out.ApplicationConfigurations
		*out = make([]ApplicationConfigurationsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttributeFormID != nil {
		in, out := &in.AttributeFormID, &out.AttributeFormID
		*out = new(string)
		**out = **in
	}
	if in.AttributeFormIDRef != nil {
		in, out := &in.AttributeFormIDRef, &out.AttributeFormIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AttributeFormIDSelector != nil {
		in, out := &in.AttributeFormIDSelector, &out.AttributeFormIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.BrandName != nil {
		in, out := &in.BrandName, &out.BrandName
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderTypeConfigurations != nil {
		in, out := &in.IdentityProviderTypeConfigurations, &out.IdentityProviderTypeConfigurations
		*out = make([]IdentityProviderTypeConfigurationsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfigurationParameters.
func (in *ManagerConfigurationParameters) DeepCopy() *ManagerConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ManagerConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfigurationSpec) DeepCopyInto(out *ManagerConfigurationSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfigurationSpec.
func (in *ManagerConfigurationSpec) DeepCopy() *ManagerConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ManagerConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfigurationStatus) DeepCopyInto(out *ManagerConfigurationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfigurationStatus.
func (in *ManagerConfigurationStatus) DeepCopy() *ManagerConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ManagerConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
