apiVersion: fusionauth.m.crossplane.io/v1alpha1
kind: Entity
metadata:
  annotations:
    meta.upbound.io/example-id: fusionauth/v1alpha1/entity
  labels:
    testing.upbound.io/example-name: raviga
  name: raviga
  namespace: crossplane-system
spec:
  forProvider:
    clientId: 092dbded-30af-4149-9c61-b578f2c72f59
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    data: |-
      ${jsonencode({
          companyType = "Legal"
        })}
    entityTypeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: company
    name: Raviga
    tenantIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: fusionauth.m.crossplane.io/v1alpha1
kind: EntityType
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/entity
  labels:
    testing.upbound.io/example-name: company
  name: company
  namespace: crossplane-system
spec:
  forProvider:
    data: |-
      ${jsonencode({
          createdBy = "jared@fusionauth.io"
        })}
    jwtConfiguration:
    - accessTokenKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      enabled: true
      timeToLiveInSeconds: 3600
    name: Company
