apiVersion: fusionauth.m.crossplane.io/v1alpha1
kind: Reactor
metadata:
  annotations:
    meta.upbound.io/example-id: fusionauth/v1alpha1/reactor
  labels:
    testing.upbound.io/example-name: reactor
  name: reactor
  namespace: crossplane-system
spec:
  forProvider:
    licenseIdSecretRef:
      key: example-key
      name: example-secret
    licenseSecretRef:
      key: example-key
      name: example-secret
