// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FormInitParameters struct {

	// A JSON string that can hold any information about the Form Field that should be persisted.
	// An object that can hold any information about the Form that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// The Id to use for the new Form. If not specified a secure random UUID will be generated.
	// The Id to use for the new Form. If not specified a secure random UUID will be generated.
	FormID *string `json:"formId,omitempty" tf:"form_id,omitempty"`

	// The unique name of the Form Field.
	// The unique name of the Form.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
	// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
	Steps []StepsInitParameters `json:"steps,omitempty" tf:"steps,omitempty"`

	// The type of step being created. The possible values are:
	// The type of form being created, a form type cannot be changed after the form has been created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FormObservation struct {

	// A JSON string that can hold any information about the Form Field that should be persisted.
	// An object that can hold any information about the Form that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// The Id to use for the new Form. If not specified a secure random UUID will be generated.
	// The Id to use for the new Form. If not specified a secure random UUID will be generated.
	FormID *string `json:"formId,omitempty" tf:"form_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The unique name of the Form Field.
	// The unique name of the Form.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
	// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
	Steps []StepsObservation `json:"steps,omitempty" tf:"steps,omitempty"`

	// The type of step being created. The possible values are:
	// The type of form being created, a form type cannot be changed after the form has been created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FormParameters struct {

	// A JSON string that can hold any information about the Form Field that should be persisted.
	// An object that can hold any information about the Form that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// The Id to use for the new Form. If not specified a secure random UUID will be generated.
	// The Id to use for the new Form. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	FormID *string `json:"formId,omitempty" tf:"form_id,omitempty"`

	// The unique name of the Form Field.
	// The unique name of the Form.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
	// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
	// +kubebuilder:validation:Optional
	Steps []StepsParameters `json:"steps,omitempty" tf:"steps,omitempty"`

	// The type of step being created. The possible values are:
	// The type of form being created, a form type cannot be changed after the form has been created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StepsInitParameters struct {

	// An ordered list of Form Field Ids assigned to this step.
	// An ordered list of Form Field Ids assigned to this step.
	Fields []*string `json:"fields,omitempty" tf:"fields,omitempty"`

	// The type of step being created. The possible values are:
	// The type of step being created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StepsObservation struct {

	// An ordered list of Form Field Ids assigned to this step.
	// An ordered list of Form Field Ids assigned to this step.
	Fields []*string `json:"fields,omitempty" tf:"fields,omitempty"`

	// The type of step being created. The possible values are:
	// The type of step being created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StepsParameters struct {

	// An ordered list of Form Field Ids assigned to this step.
	// An ordered list of Form Field Ids assigned to this step.
	// +kubebuilder:validation:Optional
	Fields []*string `json:"fields,omitempty" tf:"fields,omitempty"`

	// The type of step being created. The possible values are:
	// The type of step being created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// FormSpec defines the desired state of Form
type FormSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FormParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FormInitParameters `json:"initProvider,omitempty"`
}

// FormStatus defines the observed state of Form.
type FormStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FormObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Form is the Schema for the Forms API. Form Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,fusionauth}
type Form struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.steps) || (has(self.initProvider) && has(self.initProvider.steps))",message="spec.forProvider.steps is a required parameter"
	Spec   FormSpec   `json:"spec"`
	Status FormStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FormList contains a list of Forms
type FormList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Form `json:"items"`
}

// Repository type metadata.
var (
	Form_Kind             = "Form"
	Form_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Form_Kind}.String()
	Form_KindAPIVersion   = Form_Kind + "." + CRDGroupVersion.String()
	Form_GroupVersionKind = CRDGroupVersion.WithKind(Form_Kind)
)

func init() {
	SchemeBuilder.Register(&Form{}, &FormList{})
}
