// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RegistrationInitParameters struct {

	// The authentication token that may be used in place of the User’s password when authenticating against this application represented by this registration. This parameter is ignored if generateAuthenticationToken is set to true and instead the value will be generated.
	// The authentication token that may be used in place of the User’s password when authenticating against this application represented by this registration. This parameter is ignored if generateAuthenticationToken is set to true and instead the value will be generated.
	AuthenticationTokenSecretRef *v2.SecretKeySelector `json:"authenticationTokenSecretRef,omitempty" tf:"-"`

	// A JSON string that can hold any information about the User for this registration that should be persisted.
	// An object that can hold any information about the User Registration that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// Determines if FusionAuth should generate an Authentication Token for this registration.
	// Determines if FusionAuth should generate an Authentication Token for this registration.
	GenerateAuthenticationToken *bool `json:"generateAuthenticationToken,omitempty" tf:"generate_authentication_token,omitempty"`

	// An array of locale strings that give, in order, the User’s preferred languages for this registration. These are important for email templates and other localizable text.
	// An array of locale strings that give, in order, the User’s preferred languages for this registration. These are important for email templates and other localizable text.
	// +listType=set
	PreferredLanguages []*string `json:"preferredLanguages,omitempty" tf:"preferred_languages,omitempty"`

	// The Id of this registration. If not specified a secure random UUID will be generated.
	// The Id of this registration. If not specified a secure random UUID will be generated.
	RegistrationID *string `json:"registrationId,omitempty" tf:"registration_id,omitempty"`

	// The list of roles that the User has for this registration.
	// The list of roles that the User has for this registration.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.
	// Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.
	SkipRegistrationValidation *bool `json:"skipRegistrationValidation,omitempty" tf:"skip_registration_validation,omitempty"`

	// The User’s preferred timezone for this registration. The string will be in an IANA time zone format.
	// The User’s preferred timezone for this registration. The string will be in an IANA time zone format.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The username of the User for this registration only.
	// The username of the User for this registration only.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RegistrationObservation struct {

	// The Id of the Application that this registration is for.
	// The Id of the Application that this registration is for.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// A JSON string that can hold any information about the User for this registration that should be persisted.
	// An object that can hold any information about the User Registration that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// Determines if FusionAuth should generate an Authentication Token for this registration.
	// Determines if FusionAuth should generate an Authentication Token for this registration.
	GenerateAuthenticationToken *bool `json:"generateAuthenticationToken,omitempty" tf:"generate_authentication_token,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// An array of locale strings that give, in order, the User’s preferred languages for this registration. These are important for email templates and other localizable text.
	// An array of locale strings that give, in order, the User’s preferred languages for this registration. These are important for email templates and other localizable text.
	// +listType=set
	PreferredLanguages []*string `json:"preferredLanguages,omitempty" tf:"preferred_languages,omitempty"`

	// The Id of this registration. If not specified a secure random UUID will be generated.
	// The Id of this registration. If not specified a secure random UUID will be generated.
	RegistrationID *string `json:"registrationId,omitempty" tf:"registration_id,omitempty"`

	// The list of roles that the User has for this registration.
	// The list of roles that the User has for this registration.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.
	// Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.
	SkipRegistrationValidation *bool `json:"skipRegistrationValidation,omitempty" tf:"skip_registration_validation,omitempty"`

	// The User’s preferred timezone for this registration. The string will be in an IANA time zone format.
	// The User’s preferred timezone for this registration. The string will be in an IANA time zone format.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The Id of the User that is registering for the Application.
	// The Id of the User that is registering for the Application.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The username of the User for this registration only.
	// The username of the User for this registration only.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RegistrationParameters struct {

	// The Id of the Application that this registration is for.
	// The Id of the Application that this registration is for.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Application
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.Reference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.Selector `json:"applicationIdSelector,omitempty" tf:"-"`

	// The authentication token that may be used in place of the User’s password when authenticating against this application represented by this registration. This parameter is ignored if generateAuthenticationToken is set to true and instead the value will be generated.
	// The authentication token that may be used in place of the User’s password when authenticating against this application represented by this registration. This parameter is ignored if generateAuthenticationToken is set to true and instead the value will be generated.
	// +kubebuilder:validation:Optional
	AuthenticationTokenSecretRef *v2.SecretKeySelector `json:"authenticationTokenSecretRef,omitempty" tf:"-"`

	// A JSON string that can hold any information about the User for this registration that should be persisted.
	// An object that can hold any information about the User Registration that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// Determines if FusionAuth should generate an Authentication Token for this registration.
	// Determines if FusionAuth should generate an Authentication Token for this registration.
	// +kubebuilder:validation:Optional
	GenerateAuthenticationToken *bool `json:"generateAuthenticationToken,omitempty" tf:"generate_authentication_token,omitempty"`

	// An array of locale strings that give, in order, the User’s preferred languages for this registration. These are important for email templates and other localizable text.
	// An array of locale strings that give, in order, the User’s preferred languages for this registration. These are important for email templates and other localizable text.
	// +kubebuilder:validation:Optional
	// +listType=set
	PreferredLanguages []*string `json:"preferredLanguages,omitempty" tf:"preferred_languages,omitempty"`

	// The Id of this registration. If not specified a secure random UUID will be generated.
	// The Id of this registration. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	RegistrationID *string `json:"registrationId,omitempty" tf:"registration_id,omitempty"`

	// The list of roles that the User has for this registration.
	// The list of roles that the User has for this registration.
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.
	// Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.
	// +kubebuilder:validation:Optional
	SkipRegistrationValidation *bool `json:"skipRegistrationValidation,omitempty" tf:"skip_registration_validation,omitempty"`

	// The User’s preferred timezone for this registration. The string will be in an IANA time zone format.
	// The User’s preferred timezone for this registration. The string will be in an IANA time zone format.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The Id of the User that is registering for the Application.
	// The Id of the User that is registering for the Application.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in fusionauth to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in fusionauth to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.Selector `json:"userIdSelector,omitempty" tf:"-"`

	// The username of the User for this registration only.
	// The username of the User for this registration only.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// RegistrationSpec defines the desired state of Registration
type RegistrationSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RegistrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistrationInitParameters `json:"initProvider,omitempty"`
}

// RegistrationStatus defines the observed state of Registration.
type RegistrationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RegistrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Registration is the Schema for the Registrations API. Registration Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,fusionauth}
type Registration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RegistrationSpec   `json:"spec"`
	Status            RegistrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistrationList contains a list of Registrations
type RegistrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Registration `json:"items"`
}

// Repository type metadata.
var (
	Registration_Kind             = "Registration"
	Registration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Registration_Kind}.String()
	Registration_KindAPIVersion   = Registration_Kind + "." + CRDGroupVersion.String()
	Registration_GroupVersionKind = CRDGroupVersion.WithKind(Registration_Kind)
)

func init() {
	SchemeBuilder.Register(&Registration{}, &RegistrationList{})
}
