// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EventsEnabledInitParameters struct {

	// An audit log was created
	// An audit log was created
	AuditLogCreate *bool `json:"auditLogCreate,omitempty" tf:"audit_log_create,omitempty"`

	// An event log was created
	// An event log was created
	EventLogCreate *bool `json:"eventLogCreate,omitempty" tf:"event_log_create,omitempty"`

	// A group is being created
	// A group is being created
	GroupCreate *bool `json:"groupCreate,omitempty" tf:"group_create,omitempty"`

	// A create group request completed
	// A create group request completed
	GroupCreateComplete *bool `json:"groupCreateComplete,omitempty" tf:"group_create_complete,omitempty"`

	// A group is being deleted
	// A group is being deleted
	GroupDelete *bool `json:"groupDelete,omitempty" tf:"group_delete,omitempty"`

	// A group delete request completed
	// A group delete request completed
	GroupDeleteComplete *bool `json:"groupDeleteComplete,omitempty" tf:"group_delete_complete,omitempty"`

	// A user is being added to a group
	// A user is being added to a group
	GroupMemberAdd *bool `json:"groupMemberAdd,omitempty" tf:"group_member_add,omitempty"`

	// A user add request has completed
	// A user add request has completed
	GroupMemberAddComplete *bool `json:"groupMemberAddComplete,omitempty" tf:"group_member_add_complete,omitempty"`

	// A user is being removed from a group
	// A user is being removed from a group
	GroupMemberRemove *bool `json:"groupMemberRemove,omitempty" tf:"group_member_remove,omitempty"`

	// A user remove request has completed
	// A user remove request has completed
	GroupMemberRemoveComplete *bool `json:"groupMemberRemoveComplete,omitempty" tf:"group_member_remove_complete,omitempty"`

	// A groups membership is being updated
	// A groups membership is being updated
	GroupMemberUpdate *bool `json:"groupMemberUpdate,omitempty" tf:"group_member_update,omitempty"`

	// A group member update request has completed
	// A group member update request has completed
	GroupMemberUpdateComplete *bool `json:"groupMemberUpdateComplete,omitempty" tf:"group_member_update_complete,omitempty"`

	// A group is being updated
	// A group is being updated
	GroupUpdate *bool `json:"groupUpdate,omitempty" tf:"group_update,omitempty"`

	// A request to update a group has completed
	// A request to update a group has completed
	GroupUpdateComplete *bool `json:"groupUpdateComplete,omitempty" tf:"group_update_complete,omitempty"`

	// A configuration occurred that may affect public keys used to verify a JWT signed by FusionAuth
	// A configuration occurred that may affect public keys used to verify a JWT signed by FusionAuth
	JwtPublicKeyUpdate *bool `json:"jwtPublicKeyUpdate,omitempty" tf:"jwt_public_key_update,omitempty"`

	// A JWT was refreshed using a refresh token
	// A JWT was refreshed using a refresh token
	JwtRefresh *bool `json:"jwtRefresh,omitempty" tf:"jwt_refresh,omitempty"`

	// One or more refresh tokens were revoked
	// One or more refresh tokens were revoked
	JwtRefreshTokenRevoke *bool `json:"jwtRefreshTokenRevoke,omitempty" tf:"jwt_refresh_token_revoke,omitempty"`

	// Kickstart completed successfully the system is ready for use
	// Kickstart completed successfully the system is ready for use
	KickstartSuccess *bool `json:"kickstartSuccess,omitempty" tf:"kickstart_success,omitempty"`

	// An action was taken on a user, or an existing event may be changing states if the action is time based
	// An action was taken on a user, or an existing event may be changing states if the action is time based
	UserAction *bool `json:"userAction,omitempty" tf:"user_action,omitempty"`

	// One or more users were created using the Bulk create API
	// One or more users were created using the Bulk create API
	UserBulkCreate *bool `json:"userBulkCreate,omitempty" tf:"user_bulk_create,omitempty"`

	// A user is being created
	// A user is being created
	UserCreate *bool `json:"userCreate,omitempty" tf:"user_create,omitempty"`

	// A create user request completed
	// A create user request completed
	UserCreateComplete *bool `json:"userCreateComplete,omitempty" tf:"user_create_complete,omitempty"`

	// A user is being de-activated, this is synonymous with a soft-delete when using the API
	// A user is being de-activated, this is synonymous with a soft-delete when using the API
	UserDeactivate *bool `json:"userDeactivate,omitempty" tf:"user_deactivate,omitempty"`

	// A user is being deleted
	// A user is being deleted
	UserDelete *bool `json:"userDelete,omitempty" tf:"user_delete,omitempty"`

	// A user delete request has completed
	// A user delete request has completed
	UserDeleteComplete *bool `json:"userDeleteComplete,omitempty" tf:"user_delete_complete,omitempty"`

	// A user updated their email address
	// A user updated their email address
	UserEmailUpdate *bool `json:"userEmailUpdate,omitempty" tf:"user_email_update,omitempty"`

	// A user has verified their email address
	// A user has verified their email address
	UserEmailVerified *bool `json:"userEmailVerified,omitempty" tf:"user_email_verified,omitempty"`

	// A link has been established between a user and an identity provider
	// A link has been established between a user and an identity provider
	UserIdentityProviderLink *bool `json:"userIdentityProviderLink,omitempty" tf:"user_identity_provider_link,omitempty"`

	// An existing link has been removed between a user and an identify provider
	// An existing link has been removed between a user and an identify provider
	UserIdentityProviderUnlink *bool `json:"userIdentityProviderUnlink,omitempty" tf:"user_identity_provider_unlink,omitempty"`

	// When a user's identity is verified
	// When a user's identity is verified
	UserIdentityVerified *bool `json:"userIdentityVerified,omitempty" tf:"user_identity_verified,omitempty"`

	// A login request has failed
	// A login request has failed
	UserLoginFailed *bool `json:"userLoginFailed,omitempty" tf:"user_login_failed,omitempty"`

	// A user attempted to register using an email address or username of an existing user
	// A user attempted to register using an email address or username of an existing user
	UserLoginIDDuplicateCreate *bool `json:"userLoginIdDuplicateCreate,omitempty" tf:"user_login_id_duplicate_create,omitempty"`

	// A user attempted to modify their email address or username to that of an existing user
	// A user attempted to modify their email address or username to that of an existing user
	UserLoginIDDuplicateUpdate *bool `json:"userLoginIdDuplicateUpdate,omitempty" tf:"user_login_id_duplicate_update,omitempty"`

	// A user has logged in from a new device
	// A user has logged in from a new device
	UserLoginNewDevice *bool `json:"userLoginNewDevice,omitempty" tf:"user_login_new_device,omitempty"`

	// A login request has succeeded
	// A login request has succeeded
	UserLoginSuccess *bool `json:"userLoginSuccess,omitempty" tf:"user_login_success,omitempty"`

	// A suspicious login request has succeeded. This may be due to an impossible travel calculation, or other indicators
	// A suspicious login request has succeeded. This may be due to an impossible travel calculation, or other indicators
	UserLoginSuspicious *bool `json:"userLoginSuspicious,omitempty" tf:"user_login_suspicious,omitempty"`

	// A user's password has been identified as vulnerable due to being found in one or more breached data sets
	// A user's password has been identified as vulnerable due to being found in one or more breached data sets
	UserPasswordBreach *bool `json:"userPasswordBreach,omitempty" tf:"user_password_breach,omitempty"`

	// A user has been sent an email as part of a password reset workflow
	// A user has been sent an email as part of a password reset workflow
	UserPasswordResetSend *bool `json:"userPasswordResetSend,omitempty" tf:"user_password_reset_send,omitempty"`

	// A user has started a password reset workflow
	// A user has started a password reset workflow
	UserPasswordResetStart *bool `json:"userPasswordResetStart,omitempty" tf:"user_password_reset_start,omitempty"`

	// A user has completed a password reset workflow
	// A user has completed a password reset workflow
	UserPasswordResetSuccess *bool `json:"userPasswordResetSuccess,omitempty" tf:"user_password_reset_success,omitempty"`

	// A user has updated their password
	// A user has updated their password
	UserPasswordUpdate *bool `json:"userPasswordUpdate,omitempty" tf:"user_password_update,omitempty"`

	// A user has been re-activated
	// A user has been re-activated
	UserReactivate *bool `json:"userReactivate,omitempty" tf:"user_reactivate,omitempty"`

	// A user registration is being created
	// A user registration is being created
	UserRegistrationCreate *bool `json:"userRegistrationCreate,omitempty" tf:"user_registration_create,omitempty"`

	// A user registration has been created
	// A user registration has been created
	UserRegistrationCreateComplete *bool `json:"userRegistrationCreateComplete,omitempty" tf:"user_registration_create_complete,omitempty"`

	// A user registration has been deleted
	// A user registration has been deleted
	UserRegistrationDelete *bool `json:"userRegistrationDelete,omitempty" tf:"user_registration_delete,omitempty"`

	// A user registration delete request has completed
	// A user registration delete request has completed
	UserRegistrationDeleteComplete *bool `json:"userRegistrationDeleteComplete,omitempty" tf:"user_registration_delete_complete,omitempty"`

	// A user registration is being updated
	// A user registration is being updated
	UserRegistrationUpdate *bool `json:"userRegistrationUpdate,omitempty" tf:"user_registration_update,omitempty"`

	// A user registration update request has completed
	// A user registration update request has completed
	UserRegistrationUpdateComplete *bool `json:"userRegistrationUpdateComplete,omitempty" tf:"user_registration_update_complete,omitempty"`

	// A user registration has been verified
	// A user registration has been verified
	UserRegistrationVerified *bool `json:"userRegistrationVerified,omitempty" tf:"user_registration_verified,omitempty"`

	// A user has been issued a two-factor challenge
	// A user has been issued a two-factor challenge
	UserTwoFactorChallenge *bool `json:"userTwoFactorChallenge,omitempty" tf:"user_two_factor_challenge,omitempty"`

	// A user has failed a two-factor challenge attempt
	// A user has failed a two-factor challenge attempt
	UserTwoFactorFailedAttempt *bool `json:"userTwoFactorFailedAttempt,omitempty" tf:"user_two_factor_failed_attempt,omitempty"`

	// A user has added a two-factor method
	// A user has added a two-factor method
	UserTwoFactorMethodAdd *bool `json:"userTwoFactorMethodAdd,omitempty" tf:"user_two_factor_method_add,omitempty"`

	// A user has removed a two-factor method
	// A user has removed a two-factor method
	UserTwoFactorMethodRemove *bool `json:"userTwoFactorMethodRemove,omitempty" tf:"user_two_factor_method_remove,omitempty"`

	// A user has successfully completed a two-factor challenge
	// A user has successfully completed a two-factor challenge
	UserTwoFactorSuccess *bool `json:"userTwoFactorSuccess,omitempty" tf:"user_two_factor_success,omitempty"`

	// A user is being updated
	// A user is being updated
	UserUpdate *bool `json:"userUpdate,omitempty" tf:"user_update,omitempty"`

	// A user update request has completed
	// A user update request has completed
	UserUpdateComplete *bool `json:"userUpdateComplete,omitempty" tf:"user_update_complete,omitempty"`
}

type EventsEnabledObservation struct {

	// An audit log was created
	// An audit log was created
	AuditLogCreate *bool `json:"auditLogCreate,omitempty" tf:"audit_log_create,omitempty"`

	// An event log was created
	// An event log was created
	EventLogCreate *bool `json:"eventLogCreate,omitempty" tf:"event_log_create,omitempty"`

	// A group is being created
	// A group is being created
	GroupCreate *bool `json:"groupCreate,omitempty" tf:"group_create,omitempty"`

	// A create group request completed
	// A create group request completed
	GroupCreateComplete *bool `json:"groupCreateComplete,omitempty" tf:"group_create_complete,omitempty"`

	// A group is being deleted
	// A group is being deleted
	GroupDelete *bool `json:"groupDelete,omitempty" tf:"group_delete,omitempty"`

	// A group delete request completed
	// A group delete request completed
	GroupDeleteComplete *bool `json:"groupDeleteComplete,omitempty" tf:"group_delete_complete,omitempty"`

	// A user is being added to a group
	// A user is being added to a group
	GroupMemberAdd *bool `json:"groupMemberAdd,omitempty" tf:"group_member_add,omitempty"`

	// A user add request has completed
	// A user add request has completed
	GroupMemberAddComplete *bool `json:"groupMemberAddComplete,omitempty" tf:"group_member_add_complete,omitempty"`

	// A user is being removed from a group
	// A user is being removed from a group
	GroupMemberRemove *bool `json:"groupMemberRemove,omitempty" tf:"group_member_remove,omitempty"`

	// A user remove request has completed
	// A user remove request has completed
	GroupMemberRemoveComplete *bool `json:"groupMemberRemoveComplete,omitempty" tf:"group_member_remove_complete,omitempty"`

	// A groups membership is being updated
	// A groups membership is being updated
	GroupMemberUpdate *bool `json:"groupMemberUpdate,omitempty" tf:"group_member_update,omitempty"`

	// A group member update request has completed
	// A group member update request has completed
	GroupMemberUpdateComplete *bool `json:"groupMemberUpdateComplete,omitempty" tf:"group_member_update_complete,omitempty"`

	// A group is being updated
	// A group is being updated
	GroupUpdate *bool `json:"groupUpdate,omitempty" tf:"group_update,omitempty"`

	// A request to update a group has completed
	// A request to update a group has completed
	GroupUpdateComplete *bool `json:"groupUpdateComplete,omitempty" tf:"group_update_complete,omitempty"`

	// A configuration occurred that may affect public keys used to verify a JWT signed by FusionAuth
	// A configuration occurred that may affect public keys used to verify a JWT signed by FusionAuth
	JwtPublicKeyUpdate *bool `json:"jwtPublicKeyUpdate,omitempty" tf:"jwt_public_key_update,omitempty"`

	// A JWT was refreshed using a refresh token
	// A JWT was refreshed using a refresh token
	JwtRefresh *bool `json:"jwtRefresh,omitempty" tf:"jwt_refresh,omitempty"`

	// One or more refresh tokens were revoked
	// One or more refresh tokens were revoked
	JwtRefreshTokenRevoke *bool `json:"jwtRefreshTokenRevoke,omitempty" tf:"jwt_refresh_token_revoke,omitempty"`

	// Kickstart completed successfully the system is ready for use
	// Kickstart completed successfully the system is ready for use
	KickstartSuccess *bool `json:"kickstartSuccess,omitempty" tf:"kickstart_success,omitempty"`

	// An action was taken on a user, or an existing event may be changing states if the action is time based
	// An action was taken on a user, or an existing event may be changing states if the action is time based
	UserAction *bool `json:"userAction,omitempty" tf:"user_action,omitempty"`

	// One or more users were created using the Bulk create API
	// One or more users were created using the Bulk create API
	UserBulkCreate *bool `json:"userBulkCreate,omitempty" tf:"user_bulk_create,omitempty"`

	// A user is being created
	// A user is being created
	UserCreate *bool `json:"userCreate,omitempty" tf:"user_create,omitempty"`

	// A create user request completed
	// A create user request completed
	UserCreateComplete *bool `json:"userCreateComplete,omitempty" tf:"user_create_complete,omitempty"`

	// A user is being de-activated, this is synonymous with a soft-delete when using the API
	// A user is being de-activated, this is synonymous with a soft-delete when using the API
	UserDeactivate *bool `json:"userDeactivate,omitempty" tf:"user_deactivate,omitempty"`

	// A user is being deleted
	// A user is being deleted
	UserDelete *bool `json:"userDelete,omitempty" tf:"user_delete,omitempty"`

	// A user delete request has completed
	// A user delete request has completed
	UserDeleteComplete *bool `json:"userDeleteComplete,omitempty" tf:"user_delete_complete,omitempty"`

	// A user updated their email address
	// A user updated their email address
	UserEmailUpdate *bool `json:"userEmailUpdate,omitempty" tf:"user_email_update,omitempty"`

	// A user has verified their email address
	// A user has verified their email address
	UserEmailVerified *bool `json:"userEmailVerified,omitempty" tf:"user_email_verified,omitempty"`

	// A link has been established between a user and an identity provider
	// A link has been established between a user and an identity provider
	UserIdentityProviderLink *bool `json:"userIdentityProviderLink,omitempty" tf:"user_identity_provider_link,omitempty"`

	// An existing link has been removed between a user and an identify provider
	// An existing link has been removed between a user and an identify provider
	UserIdentityProviderUnlink *bool `json:"userIdentityProviderUnlink,omitempty" tf:"user_identity_provider_unlink,omitempty"`

	// When a user's identity is verified
	// When a user's identity is verified
	UserIdentityVerified *bool `json:"userIdentityVerified,omitempty" tf:"user_identity_verified,omitempty"`

	// A login request has failed
	// A login request has failed
	UserLoginFailed *bool `json:"userLoginFailed,omitempty" tf:"user_login_failed,omitempty"`

	// A user attempted to register using an email address or username of an existing user
	// A user attempted to register using an email address or username of an existing user
	UserLoginIDDuplicateCreate *bool `json:"userLoginIdDuplicateCreate,omitempty" tf:"user_login_id_duplicate_create,omitempty"`

	// A user attempted to modify their email address or username to that of an existing user
	// A user attempted to modify their email address or username to that of an existing user
	UserLoginIDDuplicateUpdate *bool `json:"userLoginIdDuplicateUpdate,omitempty" tf:"user_login_id_duplicate_update,omitempty"`

	// A user has logged in from a new device
	// A user has logged in from a new device
	UserLoginNewDevice *bool `json:"userLoginNewDevice,omitempty" tf:"user_login_new_device,omitempty"`

	// A login request has succeeded
	// A login request has succeeded
	UserLoginSuccess *bool `json:"userLoginSuccess,omitempty" tf:"user_login_success,omitempty"`

	// A suspicious login request has succeeded. This may be due to an impossible travel calculation, or other indicators
	// A suspicious login request has succeeded. This may be due to an impossible travel calculation, or other indicators
	UserLoginSuspicious *bool `json:"userLoginSuspicious,omitempty" tf:"user_login_suspicious,omitempty"`

	// A user's password has been identified as vulnerable due to being found in one or more breached data sets
	// A user's password has been identified as vulnerable due to being found in one or more breached data sets
	UserPasswordBreach *bool `json:"userPasswordBreach,omitempty" tf:"user_password_breach,omitempty"`

	// A user has been sent an email as part of a password reset workflow
	// A user has been sent an email as part of a password reset workflow
	UserPasswordResetSend *bool `json:"userPasswordResetSend,omitempty" tf:"user_password_reset_send,omitempty"`

	// A user has started a password reset workflow
	// A user has started a password reset workflow
	UserPasswordResetStart *bool `json:"userPasswordResetStart,omitempty" tf:"user_password_reset_start,omitempty"`

	// A user has completed a password reset workflow
	// A user has completed a password reset workflow
	UserPasswordResetSuccess *bool `json:"userPasswordResetSuccess,omitempty" tf:"user_password_reset_success,omitempty"`

	// A user has updated their password
	// A user has updated their password
	UserPasswordUpdate *bool `json:"userPasswordUpdate,omitempty" tf:"user_password_update,omitempty"`

	// A user has been re-activated
	// A user has been re-activated
	UserReactivate *bool `json:"userReactivate,omitempty" tf:"user_reactivate,omitempty"`

	// A user registration is being created
	// A user registration is being created
	UserRegistrationCreate *bool `json:"userRegistrationCreate,omitempty" tf:"user_registration_create,omitempty"`

	// A user registration has been created
	// A user registration has been created
	UserRegistrationCreateComplete *bool `json:"userRegistrationCreateComplete,omitempty" tf:"user_registration_create_complete,omitempty"`

	// A user registration has been deleted
	// A user registration has been deleted
	UserRegistrationDelete *bool `json:"userRegistrationDelete,omitempty" tf:"user_registration_delete,omitempty"`

	// A user registration delete request has completed
	// A user registration delete request has completed
	UserRegistrationDeleteComplete *bool `json:"userRegistrationDeleteComplete,omitempty" tf:"user_registration_delete_complete,omitempty"`

	// A user registration is being updated
	// A user registration is being updated
	UserRegistrationUpdate *bool `json:"userRegistrationUpdate,omitempty" tf:"user_registration_update,omitempty"`

	// A user registration update request has completed
	// A user registration update request has completed
	UserRegistrationUpdateComplete *bool `json:"userRegistrationUpdateComplete,omitempty" tf:"user_registration_update_complete,omitempty"`

	// A user registration has been verified
	// A user registration has been verified
	UserRegistrationVerified *bool `json:"userRegistrationVerified,omitempty" tf:"user_registration_verified,omitempty"`

	// A user has been issued a two-factor challenge
	// A user has been issued a two-factor challenge
	UserTwoFactorChallenge *bool `json:"userTwoFactorChallenge,omitempty" tf:"user_two_factor_challenge,omitempty"`

	// A user has failed a two-factor challenge attempt
	// A user has failed a two-factor challenge attempt
	UserTwoFactorFailedAttempt *bool `json:"userTwoFactorFailedAttempt,omitempty" tf:"user_two_factor_failed_attempt,omitempty"`

	// A user has added a two-factor method
	// A user has added a two-factor method
	UserTwoFactorMethodAdd *bool `json:"userTwoFactorMethodAdd,omitempty" tf:"user_two_factor_method_add,omitempty"`

	// A user has removed a two-factor method
	// A user has removed a two-factor method
	UserTwoFactorMethodRemove *bool `json:"userTwoFactorMethodRemove,omitempty" tf:"user_two_factor_method_remove,omitempty"`

	// A user has successfully completed a two-factor challenge
	// A user has successfully completed a two-factor challenge
	UserTwoFactorSuccess *bool `json:"userTwoFactorSuccess,omitempty" tf:"user_two_factor_success,omitempty"`

	// A user is being updated
	// A user is being updated
	UserUpdate *bool `json:"userUpdate,omitempty" tf:"user_update,omitempty"`

	// A user update request has completed
	// A user update request has completed
	UserUpdateComplete *bool `json:"userUpdateComplete,omitempty" tf:"user_update_complete,omitempty"`
}

type EventsEnabledParameters struct {

	// An audit log was created
	// An audit log was created
	// +kubebuilder:validation:Optional
	AuditLogCreate *bool `json:"auditLogCreate,omitempty" tf:"audit_log_create,omitempty"`

	// An event log was created
	// An event log was created
	// +kubebuilder:validation:Optional
	EventLogCreate *bool `json:"eventLogCreate,omitempty" tf:"event_log_create,omitempty"`

	// A group is being created
	// A group is being created
	// +kubebuilder:validation:Optional
	GroupCreate *bool `json:"groupCreate,omitempty" tf:"group_create,omitempty"`

	// A create group request completed
	// A create group request completed
	// +kubebuilder:validation:Optional
	GroupCreateComplete *bool `json:"groupCreateComplete,omitempty" tf:"group_create_complete,omitempty"`

	// A group is being deleted
	// A group is being deleted
	// +kubebuilder:validation:Optional
	GroupDelete *bool `json:"groupDelete,omitempty" tf:"group_delete,omitempty"`

	// A group delete request completed
	// A group delete request completed
	// +kubebuilder:validation:Optional
	GroupDeleteComplete *bool `json:"groupDeleteComplete,omitempty" tf:"group_delete_complete,omitempty"`

	// A user is being added to a group
	// A user is being added to a group
	// +kubebuilder:validation:Optional
	GroupMemberAdd *bool `json:"groupMemberAdd,omitempty" tf:"group_member_add,omitempty"`

	// A user add request has completed
	// A user add request has completed
	// +kubebuilder:validation:Optional
	GroupMemberAddComplete *bool `json:"groupMemberAddComplete,omitempty" tf:"group_member_add_complete,omitempty"`

	// A user is being removed from a group
	// A user is being removed from a group
	// +kubebuilder:validation:Optional
	GroupMemberRemove *bool `json:"groupMemberRemove,omitempty" tf:"group_member_remove,omitempty"`

	// A user remove request has completed
	// A user remove request has completed
	// +kubebuilder:validation:Optional
	GroupMemberRemoveComplete *bool `json:"groupMemberRemoveComplete,omitempty" tf:"group_member_remove_complete,omitempty"`

	// A groups membership is being updated
	// A groups membership is being updated
	// +kubebuilder:validation:Optional
	GroupMemberUpdate *bool `json:"groupMemberUpdate,omitempty" tf:"group_member_update,omitempty"`

	// A group member update request has completed
	// A group member update request has completed
	// +kubebuilder:validation:Optional
	GroupMemberUpdateComplete *bool `json:"groupMemberUpdateComplete,omitempty" tf:"group_member_update_complete,omitempty"`

	// A group is being updated
	// A group is being updated
	// +kubebuilder:validation:Optional
	GroupUpdate *bool `json:"groupUpdate,omitempty" tf:"group_update,omitempty"`

	// A request to update a group has completed
	// A request to update a group has completed
	// +kubebuilder:validation:Optional
	GroupUpdateComplete *bool `json:"groupUpdateComplete,omitempty" tf:"group_update_complete,omitempty"`

	// A configuration occurred that may affect public keys used to verify a JWT signed by FusionAuth
	// A configuration occurred that may affect public keys used to verify a JWT signed by FusionAuth
	// +kubebuilder:validation:Optional
	JwtPublicKeyUpdate *bool `json:"jwtPublicKeyUpdate,omitempty" tf:"jwt_public_key_update,omitempty"`

	// A JWT was refreshed using a refresh token
	// A JWT was refreshed using a refresh token
	// +kubebuilder:validation:Optional
	JwtRefresh *bool `json:"jwtRefresh,omitempty" tf:"jwt_refresh,omitempty"`

	// One or more refresh tokens were revoked
	// One or more refresh tokens were revoked
	// +kubebuilder:validation:Optional
	JwtRefreshTokenRevoke *bool `json:"jwtRefreshTokenRevoke,omitempty" tf:"jwt_refresh_token_revoke,omitempty"`

	// Kickstart completed successfully the system is ready for use
	// Kickstart completed successfully the system is ready for use
	// +kubebuilder:validation:Optional
	KickstartSuccess *bool `json:"kickstartSuccess,omitempty" tf:"kickstart_success,omitempty"`

	// An action was taken on a user, or an existing event may be changing states if the action is time based
	// An action was taken on a user, or an existing event may be changing states if the action is time based
	// +kubebuilder:validation:Optional
	UserAction *bool `json:"userAction,omitempty" tf:"user_action,omitempty"`

	// One or more users were created using the Bulk create API
	// One or more users were created using the Bulk create API
	// +kubebuilder:validation:Optional
	UserBulkCreate *bool `json:"userBulkCreate,omitempty" tf:"user_bulk_create,omitempty"`

	// A user is being created
	// A user is being created
	// +kubebuilder:validation:Optional
	UserCreate *bool `json:"userCreate,omitempty" tf:"user_create,omitempty"`

	// A create user request completed
	// A create user request completed
	// +kubebuilder:validation:Optional
	UserCreateComplete *bool `json:"userCreateComplete,omitempty" tf:"user_create_complete,omitempty"`

	// A user is being de-activated, this is synonymous with a soft-delete when using the API
	// A user is being de-activated, this is synonymous with a soft-delete when using the API
	// +kubebuilder:validation:Optional
	UserDeactivate *bool `json:"userDeactivate,omitempty" tf:"user_deactivate,omitempty"`

	// A user is being deleted
	// A user is being deleted
	// +kubebuilder:validation:Optional
	UserDelete *bool `json:"userDelete,omitempty" tf:"user_delete,omitempty"`

	// A user delete request has completed
	// A user delete request has completed
	// +kubebuilder:validation:Optional
	UserDeleteComplete *bool `json:"userDeleteComplete,omitempty" tf:"user_delete_complete,omitempty"`

	// A user updated their email address
	// A user updated their email address
	// +kubebuilder:validation:Optional
	UserEmailUpdate *bool `json:"userEmailUpdate,omitempty" tf:"user_email_update,omitempty"`

	// A user has verified their email address
	// A user has verified their email address
	// +kubebuilder:validation:Optional
	UserEmailVerified *bool `json:"userEmailVerified,omitempty" tf:"user_email_verified,omitempty"`

	// A link has been established between a user and an identity provider
	// A link has been established between a user and an identity provider
	// +kubebuilder:validation:Optional
	UserIdentityProviderLink *bool `json:"userIdentityProviderLink,omitempty" tf:"user_identity_provider_link,omitempty"`

	// An existing link has been removed between a user and an identify provider
	// An existing link has been removed between a user and an identify provider
	// +kubebuilder:validation:Optional
	UserIdentityProviderUnlink *bool `json:"userIdentityProviderUnlink,omitempty" tf:"user_identity_provider_unlink,omitempty"`

	// When a user's identity is verified
	// When a user's identity is verified
	// +kubebuilder:validation:Optional
	UserIdentityVerified *bool `json:"userIdentityVerified,omitempty" tf:"user_identity_verified,omitempty"`

	// A login request has failed
	// A login request has failed
	// +kubebuilder:validation:Optional
	UserLoginFailed *bool `json:"userLoginFailed,omitempty" tf:"user_login_failed,omitempty"`

	// A user attempted to register using an email address or username of an existing user
	// A user attempted to register using an email address or username of an existing user
	// +kubebuilder:validation:Optional
	UserLoginIDDuplicateCreate *bool `json:"userLoginIdDuplicateCreate,omitempty" tf:"user_login_id_duplicate_create,omitempty"`

	// A user attempted to modify their email address or username to that of an existing user
	// A user attempted to modify their email address or username to that of an existing user
	// +kubebuilder:validation:Optional
	UserLoginIDDuplicateUpdate *bool `json:"userLoginIdDuplicateUpdate,omitempty" tf:"user_login_id_duplicate_update,omitempty"`

	// A user has logged in from a new device
	// A user has logged in from a new device
	// +kubebuilder:validation:Optional
	UserLoginNewDevice *bool `json:"userLoginNewDevice,omitempty" tf:"user_login_new_device,omitempty"`

	// A login request has succeeded
	// A login request has succeeded
	// +kubebuilder:validation:Optional
	UserLoginSuccess *bool `json:"userLoginSuccess,omitempty" tf:"user_login_success,omitempty"`

	// A suspicious login request has succeeded. This may be due to an impossible travel calculation, or other indicators
	// A suspicious login request has succeeded. This may be due to an impossible travel calculation, or other indicators
	// +kubebuilder:validation:Optional
	UserLoginSuspicious *bool `json:"userLoginSuspicious,omitempty" tf:"user_login_suspicious,omitempty"`

	// A user's password has been identified as vulnerable due to being found in one or more breached data sets
	// A user's password has been identified as vulnerable due to being found in one or more breached data sets
	// +kubebuilder:validation:Optional
	UserPasswordBreach *bool `json:"userPasswordBreach,omitempty" tf:"user_password_breach,omitempty"`

	// A user has been sent an email as part of a password reset workflow
	// A user has been sent an email as part of a password reset workflow
	// +kubebuilder:validation:Optional
	UserPasswordResetSend *bool `json:"userPasswordResetSend,omitempty" tf:"user_password_reset_send,omitempty"`

	// A user has started a password reset workflow
	// A user has started a password reset workflow
	// +kubebuilder:validation:Optional
	UserPasswordResetStart *bool `json:"userPasswordResetStart,omitempty" tf:"user_password_reset_start,omitempty"`

	// A user has completed a password reset workflow
	// A user has completed a password reset workflow
	// +kubebuilder:validation:Optional
	UserPasswordResetSuccess *bool `json:"userPasswordResetSuccess,omitempty" tf:"user_password_reset_success,omitempty"`

	// A user has updated their password
	// A user has updated their password
	// +kubebuilder:validation:Optional
	UserPasswordUpdate *bool `json:"userPasswordUpdate,omitempty" tf:"user_password_update,omitempty"`

	// A user has been re-activated
	// A user has been re-activated
	// +kubebuilder:validation:Optional
	UserReactivate *bool `json:"userReactivate,omitempty" tf:"user_reactivate,omitempty"`

	// A user registration is being created
	// A user registration is being created
	// +kubebuilder:validation:Optional
	UserRegistrationCreate *bool `json:"userRegistrationCreate,omitempty" tf:"user_registration_create,omitempty"`

	// A user registration has been created
	// A user registration has been created
	// +kubebuilder:validation:Optional
	UserRegistrationCreateComplete *bool `json:"userRegistrationCreateComplete,omitempty" tf:"user_registration_create_complete,omitempty"`

	// A user registration has been deleted
	// A user registration has been deleted
	// +kubebuilder:validation:Optional
	UserRegistrationDelete *bool `json:"userRegistrationDelete,omitempty" tf:"user_registration_delete,omitempty"`

	// A user registration delete request has completed
	// A user registration delete request has completed
	// +kubebuilder:validation:Optional
	UserRegistrationDeleteComplete *bool `json:"userRegistrationDeleteComplete,omitempty" tf:"user_registration_delete_complete,omitempty"`

	// A user registration is being updated
	// A user registration is being updated
	// +kubebuilder:validation:Optional
	UserRegistrationUpdate *bool `json:"userRegistrationUpdate,omitempty" tf:"user_registration_update,omitempty"`

	// A user registration update request has completed
	// A user registration update request has completed
	// +kubebuilder:validation:Optional
	UserRegistrationUpdateComplete *bool `json:"userRegistrationUpdateComplete,omitempty" tf:"user_registration_update_complete,omitempty"`

	// A user registration has been verified
	// A user registration has been verified
	// +kubebuilder:validation:Optional
	UserRegistrationVerified *bool `json:"userRegistrationVerified,omitempty" tf:"user_registration_verified,omitempty"`

	// A user has been issued a two-factor challenge
	// A user has been issued a two-factor challenge
	// +kubebuilder:validation:Optional
	UserTwoFactorChallenge *bool `json:"userTwoFactorChallenge,omitempty" tf:"user_two_factor_challenge,omitempty"`

	// A user has failed a two-factor challenge attempt
	// A user has failed a two-factor challenge attempt
	// +kubebuilder:validation:Optional
	UserTwoFactorFailedAttempt *bool `json:"userTwoFactorFailedAttempt,omitempty" tf:"user_two_factor_failed_attempt,omitempty"`

	// A user has added a two-factor method
	// A user has added a two-factor method
	// +kubebuilder:validation:Optional
	UserTwoFactorMethodAdd *bool `json:"userTwoFactorMethodAdd,omitempty" tf:"user_two_factor_method_add,omitempty"`

	// A user has removed a two-factor method
	// A user has removed a two-factor method
	// +kubebuilder:validation:Optional
	UserTwoFactorMethodRemove *bool `json:"userTwoFactorMethodRemove,omitempty" tf:"user_two_factor_method_remove,omitempty"`

	// A user has successfully completed a two-factor challenge
	// A user has successfully completed a two-factor challenge
	// +kubebuilder:validation:Optional
	UserTwoFactorSuccess *bool `json:"userTwoFactorSuccess,omitempty" tf:"user_two_factor_success,omitempty"`

	// A user is being updated
	// A user is being updated
	// +kubebuilder:validation:Optional
	UserUpdate *bool `json:"userUpdate,omitempty" tf:"user_update,omitempty"`

	// A user update request has completed
	// A user update request has completed
	// +kubebuilder:validation:Optional
	UserUpdateComplete *bool `json:"userUpdateComplete,omitempty" tf:"user_update_complete,omitempty"`
}

type SignatureConfigurationInitParameters struct {

	// Whether or not webhook events are signed.
	// Indicates if the Webhook request should be signed.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The Id of the key used to sign webhook events. Required when signature_configuration is set to true.
	// The Id of the key used to sign the Webhook request.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Key
	SigningKeyID *string `json:"signingKeyId,omitempty" tf:"signing_key_id,omitempty"`

	// Reference to a Key in fusionauth to populate signingKeyId.
	// +kubebuilder:validation:Optional
	SigningKeyIDRef *v2.Reference `json:"signingKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate signingKeyId.
	// +kubebuilder:validation:Optional
	SigningKeyIDSelector *v2.Selector `json:"signingKeyIdSelector,omitempty" tf:"-"`
}

type SignatureConfigurationObservation struct {

	// Whether or not webhook events are signed.
	// Indicates if the Webhook request should be signed.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The Id of the key used to sign webhook events. Required when signature_configuration is set to true.
	// The Id of the key used to sign the Webhook request.
	SigningKeyID *string `json:"signingKeyId,omitempty" tf:"signing_key_id,omitempty"`
}

type SignatureConfigurationParameters struct {

	// Whether or not webhook events are signed.
	// Indicates if the Webhook request should be signed.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The Id of the key used to sign webhook events. Required when signature_configuration is set to true.
	// The Id of the key used to sign the Webhook request.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Key
	// +kubebuilder:validation:Optional
	SigningKeyID *string `json:"signingKeyId,omitempty" tf:"signing_key_id,omitempty"`

	// Reference to a Key in fusionauth to populate signingKeyId.
	// +kubebuilder:validation:Optional
	SigningKeyIDRef *v2.Reference `json:"signingKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate signingKeyId.
	// +kubebuilder:validation:Optional
	SigningKeyIDSelector *v2.Selector `json:"signingKeyIdSelector,omitempty" tf:"-"`
}

type WebhookInitParameters struct {

	// The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.
	ConnectTimeout *int64 `json:"connectTimeout,omitempty" tf:"connect_timeout,omitempty"`

	// A JSON string that can hold any information about the Webhook that should be persisted.
	// An object that can hold any information about the Webhook that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// A description of the Webhook. This is used for display purposes only.
	// A description of the Webhook. This is used for display purposes only.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A mapping for the events that are enabled for this Webhook.
	EventsEnabled []EventsEnabledInitParameters `json:"eventsEnabled,omitempty" tf:"events_enabled,omitempty"`

	// Whether or not this Webhook is used for all events or just for specific Applications.
	// Whether or not this Webhook is used for all events or just for specific Applications.
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// The HTTP basic authentication password that is sent as part of the HTTP request for the events.
	// The HTTP basic authentication password that is sent as part of the HTTP request for the events.
	HTTPAuthenticationPasswordSecretRef *v2.SecretKeySelector `json:"httpAuthenticationPasswordSecretRef,omitempty" tf:"-"`

	// The HTTP basic authentication username that is sent as part of the HTTP request for the events.
	// The HTTP basic authentication username that is sent as part of the HTTP request for the events.
	HTTPAuthenticationUsernameSecretRef *v2.SecretKeySelector `json:"httpAuthenticationUsernameSecretRef,omitempty" tf:"-"`

	// An object that contains headers that are sent as part of the HTTP request for the events.
	// An object that contains headers that are sent as part of the HTTP request for the events.
	Headers map[string]string `json:"headers,omitempty" tf:"headers,omitempty"`

	// The read timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// The read timeout in milliseconds used when FusionAuth sends events to the Webhook.
	ReadTimeout *int64 `json:"readTimeout,omitempty" tf:"read_timeout,omitempty"`

	// An SSL certificate in PEM format that is used to establish the a SSL (TLS specifically) connection to the Webhook.
	// An SSL certificate in PEM format that is used to establish the a SSL (TLS specifically) connection to the Webhook.
	SSLCertificate *string `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// The Id of an existing Key. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
	// The Id of an existing Key. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Key
	SSLCertificateKeyID *string `json:"sslCertificateKeyId,omitempty" tf:"ssl_certificate_key_id,omitempty"`

	// Reference to a Key in fusionauth to populate sslCertificateKeyId.
	// +kubebuilder:validation:Optional
	SSLCertificateKeyIDRef *v2.Reference `json:"sslCertificateKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate sslCertificateKeyId.
	// +kubebuilder:validation:Optional
	SSLCertificateKeyIDSelector *v2.Selector `json:"sslCertificateKeyIdSelector,omitempty" tf:"-"`

	// Configuration for webhook signing.
	SignatureConfiguration []SignatureConfigurationInitParameters `json:"signatureConfiguration,omitempty" tf:"signature_configuration,omitempty"`

	// The fully qualified URL of the Webhook’s endpoint that will accept the event requests from FusionAuth.
	// The fully qualified URL of the Webhook’s endpoint that will accept the event requests from FusionAuth.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Id to use for the new Webhook. If not specified a secure random UUID will be generated.
	// The Id of the Webhook.
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`
}

type WebhookObservation struct {

	// The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.
	ConnectTimeout *int64 `json:"connectTimeout,omitempty" tf:"connect_timeout,omitempty"`

	// A JSON string that can hold any information about the Webhook that should be persisted.
	// An object that can hold any information about the Webhook that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// A description of the Webhook. This is used for display purposes only.
	// A description of the Webhook. This is used for display purposes only.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A mapping for the events that are enabled for this Webhook.
	EventsEnabled []EventsEnabledObservation `json:"eventsEnabled,omitempty" tf:"events_enabled,omitempty"`

	// Whether or not this Webhook is used for all events or just for specific Applications.
	// Whether or not this Webhook is used for all events or just for specific Applications.
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// An object that contains headers that are sent as part of the HTTP request for the events.
	// An object that contains headers that are sent as part of the HTTP request for the events.
	Headers map[string]string `json:"headers,omitempty" tf:"headers,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The read timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// The read timeout in milliseconds used when FusionAuth sends events to the Webhook.
	ReadTimeout *int64 `json:"readTimeout,omitempty" tf:"read_timeout,omitempty"`

	// An SSL certificate in PEM format that is used to establish the a SSL (TLS specifically) connection to the Webhook.
	// An SSL certificate in PEM format that is used to establish the a SSL (TLS specifically) connection to the Webhook.
	SSLCertificate *string `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// The Id of an existing Key. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
	// The Id of an existing Key. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
	SSLCertificateKeyID *string `json:"sslCertificateKeyId,omitempty" tf:"ssl_certificate_key_id,omitempty"`

	// Configuration for webhook signing.
	SignatureConfiguration []SignatureConfigurationObservation `json:"signatureConfiguration,omitempty" tf:"signature_configuration,omitempty"`

	// The list of tenant ids that this Webhook is associated with.
	// The Ids of the Tenants that this Webhook should be associated with. If no Ids are specified and the global field is false, this Webhook will not be used.
	// +listType=set
	TenantIds []*string `json:"tenantIds,omitempty" tf:"tenant_ids,omitempty"`

	// The fully qualified URL of the Webhook’s endpoint that will accept the event requests from FusionAuth.
	// The fully qualified URL of the Webhook’s endpoint that will accept the event requests from FusionAuth.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Id to use for the new Webhook. If not specified a secure random UUID will be generated.
	// The Id of the Webhook.
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`
}

type WebhookParameters struct {

	// The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// +kubebuilder:validation:Optional
	ConnectTimeout *int64 `json:"connectTimeout,omitempty" tf:"connect_timeout,omitempty"`

	// A JSON string that can hold any information about the Webhook that should be persisted.
	// An object that can hold any information about the Webhook that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// A description of the Webhook. This is used for display purposes only.
	// A description of the Webhook. This is used for display purposes only.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A mapping for the events that are enabled for this Webhook.
	// +kubebuilder:validation:Optional
	EventsEnabled []EventsEnabledParameters `json:"eventsEnabled,omitempty" tf:"events_enabled,omitempty"`

	// Whether or not this Webhook is used for all events or just for specific Applications.
	// Whether or not this Webhook is used for all events or just for specific Applications.
	// +kubebuilder:validation:Optional
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// The HTTP basic authentication password that is sent as part of the HTTP request for the events.
	// The HTTP basic authentication password that is sent as part of the HTTP request for the events.
	// +kubebuilder:validation:Optional
	HTTPAuthenticationPasswordSecretRef *v2.SecretKeySelector `json:"httpAuthenticationPasswordSecretRef,omitempty" tf:"-"`

	// The HTTP basic authentication username that is sent as part of the HTTP request for the events.
	// The HTTP basic authentication username that is sent as part of the HTTP request for the events.
	// +kubebuilder:validation:Optional
	HTTPAuthenticationUsernameSecretRef *v2.SecretKeySelector `json:"httpAuthenticationUsernameSecretRef,omitempty" tf:"-"`

	// An object that contains headers that are sent as part of the HTTP request for the events.
	// An object that contains headers that are sent as part of the HTTP request for the events.
	// +kubebuilder:validation:Optional
	Headers map[string]string `json:"headers,omitempty" tf:"headers,omitempty"`

	// The read timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// The read timeout in milliseconds used when FusionAuth sends events to the Webhook.
	// +kubebuilder:validation:Optional
	ReadTimeout *int64 `json:"readTimeout,omitempty" tf:"read_timeout,omitempty"`

	// An SSL certificate in PEM format that is used to establish the a SSL (TLS specifically) connection to the Webhook.
	// An SSL certificate in PEM format that is used to establish the a SSL (TLS specifically) connection to the Webhook.
	// +kubebuilder:validation:Optional
	SSLCertificate *string `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// The Id of an existing Key. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
	// The Id of an existing Key. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Key
	// +kubebuilder:validation:Optional
	SSLCertificateKeyID *string `json:"sslCertificateKeyId,omitempty" tf:"ssl_certificate_key_id,omitempty"`

	// Reference to a Key in fusionauth to populate sslCertificateKeyId.
	// +kubebuilder:validation:Optional
	SSLCertificateKeyIDRef *v2.Reference `json:"sslCertificateKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate sslCertificateKeyId.
	// +kubebuilder:validation:Optional
	SSLCertificateKeyIDSelector *v2.Selector `json:"sslCertificateKeyIdSelector,omitempty" tf:"-"`

	// Configuration for webhook signing.
	// +kubebuilder:validation:Optional
	SignatureConfiguration []SignatureConfigurationParameters `json:"signatureConfiguration,omitempty" tf:"signature_configuration,omitempty"`

	// The fully qualified URL of the Webhook’s endpoint that will accept the event requests from FusionAuth.
	// The fully qualified URL of the Webhook’s endpoint that will accept the event requests from FusionAuth.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Id to use for the new Webhook. If not specified a secure random UUID will be generated.
	// The Id of the Webhook.
	// +kubebuilder:validation:Optional
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`
}

// WebhookSpec defines the desired state of Webhook
type WebhookSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   WebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WebhookInitParameters `json:"initProvider,omitempty"`
}

// WebhookStatus defines the observed state of Webhook.
type WebhookStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Webhook is the Schema for the Webhooks API. Webhook Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,fusionauth}
type Webhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.connectTimeout) || (has(self.initProvider) && has(self.initProvider.connectTimeout))",message="spec.forProvider.connectTimeout is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.readTimeout) || (has(self.initProvider) && has(self.initProvider.readTimeout))",message="spec.forProvider.readTimeout is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   WebhookSpec   `json:"spec"`
	Status WebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebhookList contains a list of Webhooks
type WebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Webhook `json:"items"`
}

// Repository type metadata.
var (
	Webhook_Kind             = "Webhook"
	Webhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Webhook_Kind}.String()
	Webhook_KindAPIVersion   = Webhook_Kind + "." + CRDGroupVersion.String()
	Webhook_GroupVersionKind = CRDGroupVersion.WithKind(Webhook_Kind)
)

func init() {
	SchemeBuilder.Register(&Webhook{}, &WebhookList{})
}
