apiVersion: idp.fusionauth.crossplane.io/v1alpha1
kind: Twitch
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/twitch
  labels:
    testing.upbound.io/example-name: twitch
  name: twitch
spec:
  forProvider:
    applicationConfiguration:
    - applicationIdSelector:
        matchLabels:
          testing.upbound.io/example-name: my_app
      createRegistration: true
      enabled: true
    buttonText: Login with Twitch
    clientId: 0eb1ce3c-2fb1-4ae9-b361-d49fc6e764cc
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    scope: Xboxlive.signin Xboxlive.offline_access
