// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OpenIDConnectApplicationConfigurationInitParameters struct {

	// ID of the Application to apply this configuration to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Application
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.NamespacedReference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.NamespacedSelector `json:"applicationIdSelector,omitempty" tf:"-"`

	// This is an optional Application specific override for the top level button image URL.
	// This is an optional Application specific override for the top level button image URL.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The top-level client id for your Application.
	// This is an optional Application specific override for the top level client id.
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// This is an optional Application specific override for the top level client secret.
	// This is an optional Application specific override for the top level client secret.
	Oauth2ClientSecretSecretRef *v2.LocalSecretKeySelector `json:"oauth2ClientSecretSecretRef,omitempty" tf:"-"`

	// This is an optional Application specific override for the top level scope.
	// This is an optional Application specific override for for the top level scope.
	Oauth2Scope *string `json:"oauth2Scope,omitempty" tf:"oauth2_scope,omitempty"`
}

type OpenIDConnectApplicationConfigurationObservation struct {

	// ID of the Application to apply this configuration to.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// This is an optional Application specific override for the top level button image URL.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The top-level client id for your Application.
	// This is an optional Application specific override for the top level client id.
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// This is an optional Application specific override for for the top level scope.
	Oauth2Scope *string `json:"oauth2Scope,omitempty" tf:"oauth2_scope,omitempty"`
}

type OpenIDConnectApplicationConfigurationParameters struct {

	// ID of the Application to apply this configuration to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Application
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.NamespacedReference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.NamespacedSelector `json:"applicationIdSelector,omitempty" tf:"-"`

	// This is an optional Application specific override for the top level button image URL.
	// This is an optional Application specific override for the top level button image URL.
	// +kubebuilder:validation:Optional
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// +kubebuilder:validation:Optional
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The top-level client id for your Application.
	// This is an optional Application specific override for the top level client id.
	// +kubebuilder:validation:Optional
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// This is an optional Application specific override for the top level client secret.
	// This is an optional Application specific override for the top level client secret.
	// +kubebuilder:validation:Optional
	Oauth2ClientSecretSecretRef *v2.LocalSecretKeySelector `json:"oauth2ClientSecretSecretRef,omitempty" tf:"-"`

	// This is an optional Application specific override for the top level scope.
	// This is an optional Application specific override for for the top level scope.
	// +kubebuilder:validation:Optional
	Oauth2Scope *string `json:"oauth2Scope,omitempty" tf:"oauth2_scope,omitempty"`
}

type OpenIDConnectInitParameters struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	ApplicationConfiguration []OpenIDConnectApplicationConfigurationInitParameters `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// +listType=set
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Lambda
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// Reference to a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDRef *v2.NamespacedReference `json:"lambdaReconcileIdRef,omitempty" tf:"-"`

	// Selector for a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDSelector *v2.NamespacedSelector `json:"lambdaReconcileIdSelector,omitempty" tf:"-"`

	// The linking strategy to use when creating the link between the OpenID Connect Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the OpenID Connect Identity Provider and the user.
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The name of this OpenID Connect identity provider. This is only used for display purposes.
	// The name of the provider. This is only used for display purposes.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the authorization endpoint. If you provide an issuer then this field will be ignored.
	// The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the authorization endpoint. If you provide an issuer then this field will be ignored.
	Oauth2AuthorizationEndpoint *string `json:"oauth2AuthorizationEndpoint,omitempty" tf:"oauth2_authorization_endpoint,omitempty"`

	// The client authentication method to use with the OpenID Connect identity provider.
	// The client authentication method to use with the OpenID Connect identity provider.
	Oauth2ClientAuthenticationMethod *string `json:"oauth2ClientAuthenticationMethod,omitempty" tf:"oauth2_client_authentication_method,omitempty"`

	// The top-level client id for your Application.
	// The top-level client id for your Application.
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// This is an optional Application specific override for the top level client secret.
	// The top-level client secret to use with the OpenID Connect identity provider.
	Oauth2ClientSecretSecretRef *v2.LocalSecretKeySelector `json:"oauth2ClientSecretSecretRef,omitempty" tf:"-"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.
	Oauth2EmailClaim *string `json:"oauth2EmailClaim,omitempty" tf:"oauth2_email_claim,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email verified status.
	// An optional configuration to modify the expected name of the claim returned by the IdP that indicates if the email is verified.
	Oauth2EmailVerifiedClaim *string `json:"oauth2EmailVerifiedClaim,omitempty" tf:"oauth2_email_verified_claim,omitempty"`

	// The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the issuer URI plus /.well-known/openid-configuration.
	// The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the issuer URI plus /.well-known/openid-configuration.
	Oauth2Issuer *string `json:"oauth2Issuer,omitempty" tf:"oauth2_issuer,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// The top-level scope that you are requesting from the OpenID Connect identity provider.
	Oauth2Scope *string `json:"oauth2Scope,omitempty" tf:"oauth2_scope,omitempty"`

	// The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the token endpoint. If you provide an issuer then this field will be ignored.
	// The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the token endpoint. If you provide an issuer then this field will be ignored.
	Oauth2TokenEndpoint *string `json:"oauth2TokenEndpoint,omitempty" tf:"oauth2_token_endpoint,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the user Id.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the user Id.
	Oauth2UniqueIDClaim *string `json:"oauth2UniqueIdClaim,omitempty" tf:"oauth2_unique_id_claim,omitempty"`

	// The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the userinfo endpoint. If you provide an issuer then this field will be ignored.
	// The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the userinfo endpoint. If you provide an issuer then this field will be ignored.
	Oauth2UserInfoEndpoint *string `json:"oauth2UserInfoEndpoint,omitempty" tf:"oauth2_user_info_endpoint,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the username.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the username.
	Oauth2UsernameClaim *string `json:"oauth2UsernameClaim,omitempty" tf:"oauth2_username_claim,omitempty"`

	// Set this value equal to true if you wish to use POST bindings with this OpenID Connect identity provider. The default value of false means that a redirect binding which uses a GET request will be used.
	// Set this value equal to true if you wish to use POST bindings with this OpenID Connect identity provider. The default value of false means that a redirect binding which uses a GET request will be used.
	PostRequest *bool `json:"postRequest,omitempty" tf:"post_request,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	TenantConfiguration []OpenIDConnectTenantConfigurationInitParameters `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type OpenIDConnectObservation struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	ApplicationConfiguration []OpenIDConnectApplicationConfigurationObservation `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// +listType=set
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// The linking strategy to use when creating the link between the OpenID Connect Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the OpenID Connect Identity Provider and the user.
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The name of this OpenID Connect identity provider. This is only used for display purposes.
	// The name of the provider. This is only used for display purposes.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the authorization endpoint. If you provide an issuer then this field will be ignored.
	// The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the authorization endpoint. If you provide an issuer then this field will be ignored.
	Oauth2AuthorizationEndpoint *string `json:"oauth2AuthorizationEndpoint,omitempty" tf:"oauth2_authorization_endpoint,omitempty"`

	// The client authentication method to use with the OpenID Connect identity provider.
	// The client authentication method to use with the OpenID Connect identity provider.
	Oauth2ClientAuthenticationMethod *string `json:"oauth2ClientAuthenticationMethod,omitempty" tf:"oauth2_client_authentication_method,omitempty"`

	// The top-level client id for your Application.
	// The top-level client id for your Application.
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.
	Oauth2EmailClaim *string `json:"oauth2EmailClaim,omitempty" tf:"oauth2_email_claim,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email verified status.
	// An optional configuration to modify the expected name of the claim returned by the IdP that indicates if the email is verified.
	Oauth2EmailVerifiedClaim *string `json:"oauth2EmailVerifiedClaim,omitempty" tf:"oauth2_email_verified_claim,omitempty"`

	// The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the issuer URI plus /.well-known/openid-configuration.
	// The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the issuer URI plus /.well-known/openid-configuration.
	Oauth2Issuer *string `json:"oauth2Issuer,omitempty" tf:"oauth2_issuer,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// The top-level scope that you are requesting from the OpenID Connect identity provider.
	Oauth2Scope *string `json:"oauth2Scope,omitempty" tf:"oauth2_scope,omitempty"`

	// The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the token endpoint. If you provide an issuer then this field will be ignored.
	// The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the token endpoint. If you provide an issuer then this field will be ignored.
	Oauth2TokenEndpoint *string `json:"oauth2TokenEndpoint,omitempty" tf:"oauth2_token_endpoint,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the user Id.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the user Id.
	Oauth2UniqueIDClaim *string `json:"oauth2UniqueIdClaim,omitempty" tf:"oauth2_unique_id_claim,omitempty"`

	// The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the userinfo endpoint. If you provide an issuer then this field will be ignored.
	// The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the userinfo endpoint. If you provide an issuer then this field will be ignored.
	Oauth2UserInfoEndpoint *string `json:"oauth2UserInfoEndpoint,omitempty" tf:"oauth2_user_info_endpoint,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the username.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the username.
	Oauth2UsernameClaim *string `json:"oauth2UsernameClaim,omitempty" tf:"oauth2_username_claim,omitempty"`

	// Set this value equal to true if you wish to use POST bindings with this OpenID Connect identity provider. The default value of false means that a redirect binding which uses a GET request will be used.
	// Set this value equal to true if you wish to use POST bindings with this OpenID Connect identity provider. The default value of false means that a redirect binding which uses a GET request will be used.
	PostRequest *bool `json:"postRequest,omitempty" tf:"post_request,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	TenantConfiguration []OpenIDConnectTenantConfigurationObservation `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type OpenIDConnectParameters struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	// +kubebuilder:validation:Optional
	ApplicationConfiguration []OpenIDConnectApplicationConfigurationParameters `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
	// +kubebuilder:validation:Optional
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// +kubebuilder:validation:Optional
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// +kubebuilder:validation:Optional
	// +listType=set
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Lambda
	// +kubebuilder:validation:Optional
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// Reference to a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDRef *v2.NamespacedReference `json:"lambdaReconcileIdRef,omitempty" tf:"-"`

	// Selector for a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDSelector *v2.NamespacedSelector `json:"lambdaReconcileIdSelector,omitempty" tf:"-"`

	// The linking strategy to use when creating the link between the OpenID Connect Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the OpenID Connect Identity Provider and the user.
	// +kubebuilder:validation:Optional
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The name of this OpenID Connect identity provider. This is only used for display purposes.
	// The name of the provider. This is only used for display purposes.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the authorization endpoint. If you provide an issuer then this field will be ignored.
	// The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the authorization endpoint. If you provide an issuer then this field will be ignored.
	// +kubebuilder:validation:Optional
	Oauth2AuthorizationEndpoint *string `json:"oauth2AuthorizationEndpoint,omitempty" tf:"oauth2_authorization_endpoint,omitempty"`

	// The client authentication method to use with the OpenID Connect identity provider.
	// The client authentication method to use with the OpenID Connect identity provider.
	// +kubebuilder:validation:Optional
	Oauth2ClientAuthenticationMethod *string `json:"oauth2ClientAuthenticationMethod,omitempty" tf:"oauth2_client_authentication_method,omitempty"`

	// The top-level client id for your Application.
	// The top-level client id for your Application.
	// +kubebuilder:validation:Optional
	Oauth2ClientID *string `json:"oauth2ClientId,omitempty" tf:"oauth2_client_id,omitempty"`

	// This is an optional Application specific override for the top level client secret.
	// The top-level client secret to use with the OpenID Connect identity provider.
	// +kubebuilder:validation:Optional
	Oauth2ClientSecretSecretRef *v2.LocalSecretKeySelector `json:"oauth2ClientSecretSecretRef,omitempty" tf:"-"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.
	// +kubebuilder:validation:Optional
	Oauth2EmailClaim *string `json:"oauth2EmailClaim,omitempty" tf:"oauth2_email_claim,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the email verified status.
	// An optional configuration to modify the expected name of the claim returned by the IdP that indicates if the email is verified.
	// +kubebuilder:validation:Optional
	Oauth2EmailVerifiedClaim *string `json:"oauth2EmailVerifiedClaim,omitempty" tf:"oauth2_email_verified_claim,omitempty"`

	// The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the issuer URI plus /.well-known/openid-configuration.
	// The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the issuer URI plus /.well-known/openid-configuration.
	// +kubebuilder:validation:Optional
	Oauth2Issuer *string `json:"oauth2Issuer,omitempty" tf:"oauth2_issuer,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// The top-level scope that you are requesting from the OpenID Connect identity provider.
	// +kubebuilder:validation:Optional
	Oauth2Scope *string `json:"oauth2Scope,omitempty" tf:"oauth2_scope,omitempty"`

	// The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the token endpoint. If you provide an issuer then this field will be ignored.
	// The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the token endpoint. If you provide an issuer then this field will be ignored.
	// +kubebuilder:validation:Optional
	Oauth2TokenEndpoint *string `json:"oauth2TokenEndpoint,omitempty" tf:"oauth2_token_endpoint,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the user Id.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the user Id.
	// +kubebuilder:validation:Optional
	Oauth2UniqueIDClaim *string `json:"oauth2UniqueIdClaim,omitempty" tf:"oauth2_unique_id_claim,omitempty"`

	// The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the userinfo endpoint. If you provide an issuer then this field will be ignored.
	// The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the issuer field, which will be used to make a request to the OpenID Connect .well-known endpoint in order to dynamically resolve the userinfo endpoint. If you provide an issuer then this field will be ignored.
	// +kubebuilder:validation:Optional
	Oauth2UserInfoEndpoint *string `json:"oauth2UserInfoEndpoint,omitempty" tf:"oauth2_user_info_endpoint,omitempty"`

	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the username.
	// An optional configuration to modify the expected name of the claim returned by the IdP that contains the username.
	// +kubebuilder:validation:Optional
	Oauth2UsernameClaim *string `json:"oauth2UsernameClaim,omitempty" tf:"oauth2_username_claim,omitempty"`

	// Set this value equal to true if you wish to use POST bindings with this OpenID Connect identity provider. The default value of false means that a redirect binding which uses a GET request will be used.
	// Set this value equal to true if you wish to use POST bindings with this OpenID Connect identity provider. The default value of false means that a redirect binding which uses a GET request will be used.
	// +kubebuilder:validation:Optional
	PostRequest *bool `json:"postRequest,omitempty" tf:"post_request,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// +kubebuilder:validation:Optional
	TenantConfiguration []OpenIDConnectTenantConfigurationParameters `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type OpenIDConnectTenantConfigurationInitParameters struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type OpenIDConnectTenantConfigurationObservation struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type OpenIDConnectTenantConfigurationParameters struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	// +kubebuilder:validation:Optional
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// +kubebuilder:validation:Optional
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`
}

// OpenIDConnectSpec defines the desired state of OpenIDConnect
type OpenIDConnectSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OpenIDConnectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OpenIDConnectInitParameters `json:"initProvider,omitempty"`
}

// OpenIDConnectStatus defines the observed state of OpenIDConnect.
type OpenIDConnectStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OpenIDConnectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OpenIDConnect is the Schema for the OpenIDConnects API. OpenID Connect Identity Provider Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,fusionauth}
type OpenIDConnect struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.buttonText) || (has(self.initProvider) && has(self.initProvider.buttonText))",message="spec.forProvider.buttonText is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oauth2ClientId) || (has(self.initProvider) && has(self.initProvider.oauth2ClientId))",message="spec.forProvider.oauth2ClientId is a required parameter"
	Spec   OpenIDConnectSpec   `json:"spec"`
	Status OpenIDConnectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OpenIDConnectList contains a list of OpenIDConnects
type OpenIDConnectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OpenIDConnect `json:"items"`
}

// Repository type metadata.
var (
	OpenIDConnect_Kind             = "OpenIDConnect"
	OpenIDConnect_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OpenIDConnect_Kind}.String()
	OpenIDConnect_KindAPIVersion   = OpenIDConnect_Kind + "." + CRDGroupVersion.String()
	OpenIDConnect_GroupVersionKind = CRDGroupVersion.WithKind(OpenIDConnect_Kind)
)

func init() {
	SchemeBuilder.Register(&OpenIDConnect{}, &OpenIDConnectList{})
}
