// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AssertionConfigurationInitParameters struct {

	// The configuration for the SAML assertion decryption.
	// The decryption configuration for the SAML v2 identity provider.
	Decryption []DecryptionInitParameters `json:"decryption,omitempty" tf:"decryption,omitempty"`

	// The array of URLs that FusionAuth will accept as SAML login destinations if the policy setting is AllowAlternates.
	// The destination of the assertion.
	Destination []DestinationInitParameters `json:"destination,omitempty" tf:"destination,omitempty"`
}

type AssertionConfigurationObservation struct {

	// The configuration for the SAML assertion decryption.
	// The decryption configuration for the SAML v2 identity provider.
	Decryption []DecryptionObservation `json:"decryption,omitempty" tf:"decryption,omitempty"`

	// The array of URLs that FusionAuth will accept as SAML login destinations if the policy setting is AllowAlternates.
	// The destination of the assertion.
	Destination []DestinationObservation `json:"destination,omitempty" tf:"destination,omitempty"`
}

type AssertionConfigurationParameters struct {

	// The configuration for the SAML assertion decryption.
	// The decryption configuration for the SAML v2 identity provider.
	// +kubebuilder:validation:Optional
	Decryption []DecryptionParameters `json:"decryption,omitempty" tf:"decryption,omitempty"`

	// The array of URLs that FusionAuth will accept as SAML login destinations if the policy setting is AllowAlternates.
	// The destination of the assertion.
	// +kubebuilder:validation:Optional
	Destination []DestinationParameters `json:"destination,omitempty" tf:"destination,omitempty"`
}

type DecryptionInitParameters struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if FusionAuth requires encrypted assertions in SAML responses from the identity provider. When true, SAML responses from the identity provider containing unencrypted assertions will be rejected by FusionAuth.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The Id of the key stored in Key Master that is used to decrypt the symmetric key on the SAML response sent to FusionAuth from the identity provider. The selected Key must contain an RSA private key. Required when enabled is true.
	// The Id of the key stored in Key Master that is used to decrypt the symmetric key on the SAML response sent to FusionAuth from the identity provider. The selected Key must contain an RSA private key. Required when `'enabled` is true.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Key
	KeyTransportDecryptionKeyID *string `json:"keyTransportDecryptionKeyId,omitempty" tf:"key_transport_decryption_key_id,omitempty"`

	// Reference to a Key in fusionauth to populate keyTransportDecryptionKeyId.
	// +kubebuilder:validation:Optional
	KeyTransportDecryptionKeyIDRef *v2.NamespacedReference `json:"keyTransportDecryptionKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate keyTransportDecryptionKeyId.
	// +kubebuilder:validation:Optional
	KeyTransportDecryptionKeyIDSelector *v2.NamespacedSelector `json:"keyTransportDecryptionKeyIdSelector,omitempty" tf:"-"`
}

type DecryptionObservation struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if FusionAuth requires encrypted assertions in SAML responses from the identity provider. When true, SAML responses from the identity provider containing unencrypted assertions will be rejected by FusionAuth.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The Id of the key stored in Key Master that is used to decrypt the symmetric key on the SAML response sent to FusionAuth from the identity provider. The selected Key must contain an RSA private key. Required when enabled is true.
	// The Id of the key stored in Key Master that is used to decrypt the symmetric key on the SAML response sent to FusionAuth from the identity provider. The selected Key must contain an RSA private key. Required when `'enabled` is true.
	KeyTransportDecryptionKeyID *string `json:"keyTransportDecryptionKeyId,omitempty" tf:"key_transport_decryption_key_id,omitempty"`
}

type DecryptionParameters struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if FusionAuth requires encrypted assertions in SAML responses from the identity provider. When true, SAML responses from the identity provider containing unencrypted assertions will be rejected by FusionAuth.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The Id of the key stored in Key Master that is used to decrypt the symmetric key on the SAML response sent to FusionAuth from the identity provider. The selected Key must contain an RSA private key. Required when enabled is true.
	// The Id of the key stored in Key Master that is used to decrypt the symmetric key on the SAML response sent to FusionAuth from the identity provider. The selected Key must contain an RSA private key. Required when `'enabled` is true.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Key
	// +kubebuilder:validation:Optional
	KeyTransportDecryptionKeyID *string `json:"keyTransportDecryptionKeyId,omitempty" tf:"key_transport_decryption_key_id,omitempty"`

	// Reference to a Key in fusionauth to populate keyTransportDecryptionKeyId.
	// +kubebuilder:validation:Optional
	KeyTransportDecryptionKeyIDRef *v2.NamespacedReference `json:"keyTransportDecryptionKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate keyTransportDecryptionKeyId.
	// +kubebuilder:validation:Optional
	KeyTransportDecryptionKeyIDSelector *v2.NamespacedSelector `json:"keyTransportDecryptionKeyIdSelector,omitempty" tf:"-"`
}

type DestinationInitParameters struct {

	// The alternate destinations of the assertion.
	// The array of URLs that FusionAuth will accept as SAML login destinations if the identityProvider.assertionConfiguration.destination.policy setting is AllowAlternates.
	Alternates []*string `json:"alternates,omitempty" tf:"alternates,omitempty"`

	// The policy to use when performing a destination assertion on the SAML login request. The possible values are Enabled, Disabled, and AllowAlternates.
	// The policy to use when performing a destination assertion on the SAML login request. The possible values are: Enabled, Disabled and AllowAlternates.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type DestinationObservation struct {

	// The alternate destinations of the assertion.
	// The array of URLs that FusionAuth will accept as SAML login destinations if the identityProvider.assertionConfiguration.destination.policy setting is AllowAlternates.
	Alternates []*string `json:"alternates,omitempty" tf:"alternates,omitempty"`

	// The policy to use when performing a destination assertion on the SAML login request. The possible values are Enabled, Disabled, and AllowAlternates.
	// The policy to use when performing a destination assertion on the SAML login request. The possible values are: Enabled, Disabled and AllowAlternates.
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type DestinationParameters struct {

	// The alternate destinations of the assertion.
	// The array of URLs that FusionAuth will accept as SAML login destinations if the identityProvider.assertionConfiguration.destination.policy setting is AllowAlternates.
	// +kubebuilder:validation:Optional
	Alternates []*string `json:"alternates,omitempty" tf:"alternates,omitempty"`

	// The policy to use when performing a destination assertion on the SAML login request. The possible values are Enabled, Disabled, and AllowAlternates.
	// The policy to use when performing a destination assertion on the SAML login request. The possible values are: Enabled, Disabled and AllowAlternates.
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type IdpInitiatedConfigurationInitParameters struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if FusionAuth will accept IdP initiated login requests from this SAMLv2 Identity Provider.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when enabled is true.
	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when `enabled` is true.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`
}

type IdpInitiatedConfigurationObservation struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if FusionAuth will accept IdP initiated login requests from this SAMLv2 Identity Provider.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when enabled is true.
	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when `enabled` is true.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`
}

type IdpInitiatedConfigurationParameters struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if FusionAuth will accept IdP initiated login requests from this SAMLv2 Identity Provider.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when enabled is true.
	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when `enabled` is true.
	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`
}

type LoginHintConfigurationInitParameters struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// When enabled and HTTP-Redirect bindings are used, FusionAuth will provide the username or email address when available to the IdP as a login hint using the configured parameter name set by the identityProvider.loginHintConfiguration.parameterName to initiate the AuthN request.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request. The default value is login_hint. Required when enabled is true.
	// The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request.
	ParameterName *string `json:"parameterName,omitempty" tf:"parameter_name,omitempty"`
}

type LoginHintConfigurationObservation struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// When enabled and HTTP-Redirect bindings are used, FusionAuth will provide the username or email address when available to the IdP as a login hint using the configured parameter name set by the identityProvider.loginHintConfiguration.parameterName to initiate the AuthN request.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request. The default value is login_hint. Required when enabled is true.
	// The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request.
	ParameterName *string `json:"parameterName,omitempty" tf:"parameter_name,omitempty"`
}

type LoginHintConfigurationParameters struct {

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// When enabled and HTTP-Redirect bindings are used, FusionAuth will provide the username or email address when available to the IdP as a login hint using the configured parameter name set by the identityProvider.loginHintConfiguration.parameterName to initiate the AuthN request.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request. The default value is login_hint. Required when enabled is true.
	// The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request.
	// +kubebuilder:validation:Optional
	ParameterName *string `json:"parameterName,omitempty" tf:"parameter_name,omitempty"`
}

type SAMLV2ApplicationConfigurationInitParameters struct {

	// ID of the Application to apply this configuration to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Application
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.NamespacedReference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.NamespacedSelector `json:"applicationIdSelector,omitempty" tf:"-"`

	// This is an optional Application specific override for the top level button image URL.
	// This is an optional Application specific override for the top level button image URL.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type SAMLV2ApplicationConfigurationObservation struct {

	// ID of the Application to apply this configuration to.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// This is an optional Application specific override for the top level button image URL.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type SAMLV2ApplicationConfigurationParameters struct {

	// ID of the Application to apply this configuration to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Application
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.NamespacedReference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.NamespacedSelector `json:"applicationIdSelector,omitempty" tf:"-"`

	// This is an optional Application specific override for the top level button image URL.
	// This is an optional Application specific override for the top level button image URL.
	// +kubebuilder:validation:Optional
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// +kubebuilder:validation:Optional
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type SAMLV2InitParameters struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	ApplicationConfiguration []SAMLV2ApplicationConfigurationInitParameters `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// The configuration for the SAML assertion.
	// The assertion configuration for the SAML v2 identity provider.
	AssertionConfiguration []AssertionConfigurationInitParameters `json:"assertionConfiguration,omitempty" tf:"assertion_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// +listType=set
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// The name of the email claim (Attribute in the Assertion element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the use_name_for_email flag must be true.
	// The name of the email claim (Attribute in the Assertion element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the `use_name_for_email` flag must be true.
	EmailClaim *string `json:"emailClaim,omitempty" tf:"email_claim,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The SAML v2 login page of the identity provider.
	// The SAML v2 login page of the identity provider.
	IdpEndpoint *string `json:"idpEndpoint,omitempty" tf:"idp_endpoint,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The configuration for the IdP initiated login.
	// The configuration for the IdP initiated login.
	IdpInitiatedConfiguration []IdpInitiatedConfigurationInitParameters `json:"idpInitiatedConfiguration,omitempty" tf:"idp_initiated_configuration,omitempty"`

	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when enabled is true.
	// The EntityId (unique identifier) FusionAuth uses as the SAML service provider. FusionAuth expects the Audience value in the SAML assertion to match this value. When not provided, FusionAuth uses the default service provider EntityId of `<base_url>/samlv2/sp/<identityProviderId>`; that default is applied when serving metadata and validating assertions and is not stored on the identity provider, so this attribute stays empty until you set it explicitly. This value is not required to be a URI, but it must not be an empty string when provided.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component). In version 1.69.0 and above, use verification_key_ids instead. This field will continue to be populated with the first entry in verification_key_ids for backward compatibility, so removing it from your configuration no longer clears it. Set verification_key_ids instead. Exactly one of key_id or verification_key_ids must be set. See the 1.69.0 Key Configuration Migration Guide.
	// The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Key
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Reference to a Key in fusionauth to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDRef *v2.NamespacedReference `json:"keyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDSelector *v2.NamespacedSelector `json:"keyIdSelector,omitempty" tf:"-"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Lambda
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// Reference to a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDRef *v2.NamespacedReference `json:"lambdaReconcileIdRef,omitempty" tf:"-"`

	// Selector for a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDSelector *v2.NamespacedSelector `json:"lambdaReconcileIdSelector,omitempty" tf:"-"`

	// The linking strategy to use when creating the link between the SAML v2 Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the SAML v2 Identity Provider and the user.
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The configuration for the login hint.
	// The configuration for the login hint.
	LoginHintConfiguration []LoginHintConfigurationInitParameters `json:"loginHintConfiguration,omitempty" tf:"login_hint_configuration,omitempty"`

	// The name of this OpenID Connect identity provider. This is only used for display purposes.
	// The name of the provider. This is only used for display purposes.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response. When this parameter is omitted a default value of urn:oasis:names:tc:SAML:2.0:nameid-format:persistent will be used.
	// The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response. When this parameter is omitted a default value of urn:oasis:names:tc:SAML:2.0:nameid-format:persistent will be used.
	NameIDFormat *string `json:"nameIdFormat,omitempty" tf:"name_id_format,omitempty"`

	// When true the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
	// When true the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
	PostRequest *bool `json:"postRequest,omitempty" tf:"post_request,omitempty"`

	// The key pair Id to use to sign the SAML request. Required when sign_request is true.
	// The key pair Id to use to sign the SAML request. Required when `sign_request` is true.
	RequestSigningKey *string `json:"requestSigningKey,omitempty" tf:"request_signing_key,omitempty"`

	// When true authentication requests sent to the identity provider will be signed.
	// When true authentication requests sent to the identity provider will be signed.
	SignRequest *bool `json:"signRequest,omitempty" tf:"sign_request,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	TenantConfiguration []SAMLV2TenantConfigurationInitParameters `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`

	// The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the email_claim will be used when linking user.
	// The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the emailClaim will be used when linking user.
	UniqueIDClaim *string `json:"uniqueIdClaim,omitempty" tf:"unique_id_claim,omitempty"`

	// Whether or not FusionAuth will use the NameID element value as the email address of the user for reconciliation processing. If this is false, then the email_claim property must be set.
	// Whether or not FusionAuth will use the NameID element value as the email address of the user for reconciliation processing. If this is false, then the `email_claim` property must be set.
	UseNameForEmail *bool `json:"useNameForEmail,omitempty" tf:"use_name_for_email,omitempty"`

	// The name of the claim in the SAML response that FusionAuth uses to identify the username. If this is not set, the NameId value will be used to link a user. This property is required when linkingStrategy is set to LinkByUsername or LinkByUsernameForExistingUser.
	// The name of the claim in the SAML response that FusionAuth uses to identify the username. If this is not set, the NameId value will be used to link a user. This property is required when linkingStrategy is set to LinkByUsername or LinkByUsernameForExistingUser.
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`

	// The Ids of the keys stored in Key Master that are used to verify the SAML response sent back to FusionAuth from the identity provider. These keys must be verification only keys or certificates (meaning that they only have a public key component). The first entry is the default verification key and is the value FusionAuth reports back in key_id. Exactly one of key_id or verification_key_ids must be set. Requires FusionAuth 1.69.0 or later.
	// The Ids of the keys stored in Key Master that are used to verify the SAML response sent back to FusionAuth from the identity provider. These keys must be verification only keys or certificates (meaning that they only have a public key component). The first entry is the default verification key. Requires FusionAuth 1.69.0 or later.
	VerificationKeyIds []*string `json:"verificationKeyIds,omitempty" tf:"verification_key_ids,omitempty"`

	// The XML signature canonicalization method used when digesting and signing the SAML request.
	// The XML signature canonicalization method used when digesting and signing the SAML request.
	XMLSignatureCanonicalizationMethod *string `json:"xmlSignatureCanonicalizationMethod,omitempty" tf:"xml_signature_canonicalization_method,omitempty"`
}

type SAMLV2Observation struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	ApplicationConfiguration []SAMLV2ApplicationConfigurationObservation `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// The configuration for the SAML assertion.
	// The assertion configuration for the SAML v2 identity provider.
	AssertionConfiguration []AssertionConfigurationObservation `json:"assertionConfiguration,omitempty" tf:"assertion_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// +listType=set
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// The name of the email claim (Attribute in the Assertion element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the use_name_for_email flag must be true.
	// The name of the email claim (Attribute in the Assertion element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the `use_name_for_email` flag must be true.
	EmailClaim *string `json:"emailClaim,omitempty" tf:"email_claim,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The SAML v2 login page of the identity provider.
	// The SAML v2 login page of the identity provider.
	IdpEndpoint *string `json:"idpEndpoint,omitempty" tf:"idp_endpoint,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The configuration for the IdP initiated login.
	// The configuration for the IdP initiated login.
	IdpInitiatedConfiguration []IdpInitiatedConfigurationObservation `json:"idpInitiatedConfiguration,omitempty" tf:"idp_initiated_configuration,omitempty"`

	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when enabled is true.
	// The EntityId (unique identifier) FusionAuth uses as the SAML service provider. FusionAuth expects the Audience value in the SAML assertion to match this value. When not provided, FusionAuth uses the default service provider EntityId of `<base_url>/samlv2/sp/<identityProviderId>`; that default is applied when serving metadata and validating assertions and is not stored on the identity provider, so this attribute stays empty until you set it explicitly. This value is not required to be a URI, but it must not be an empty string when provided.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component). In version 1.69.0 and above, use verification_key_ids instead. This field will continue to be populated with the first entry in verification_key_ids for backward compatibility, so removing it from your configuration no longer clears it. Set verification_key_ids instead. Exactly one of key_id or verification_key_ids must be set. See the 1.69.0 Key Configuration Migration Guide.
	// The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// The linking strategy to use when creating the link between the SAML v2 Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the SAML v2 Identity Provider and the user.
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The configuration for the login hint.
	// The configuration for the login hint.
	LoginHintConfiguration []LoginHintConfigurationObservation `json:"loginHintConfiguration,omitempty" tf:"login_hint_configuration,omitempty"`

	// The name of this OpenID Connect identity provider. This is only used for display purposes.
	// The name of the provider. This is only used for display purposes.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response. When this parameter is omitted a default value of urn:oasis:names:tc:SAML:2.0:nameid-format:persistent will be used.
	// The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response. When this parameter is omitted a default value of urn:oasis:names:tc:SAML:2.0:nameid-format:persistent will be used.
	NameIDFormat *string `json:"nameIdFormat,omitempty" tf:"name_id_format,omitempty"`

	// When true the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
	// When true the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
	PostRequest *bool `json:"postRequest,omitempty" tf:"post_request,omitempty"`

	// The key pair Id to use to sign the SAML request. Required when sign_request is true.
	// The key pair Id to use to sign the SAML request. Required when `sign_request` is true.
	RequestSigningKey *string `json:"requestSigningKey,omitempty" tf:"request_signing_key,omitempty"`

	// When true authentication requests sent to the identity provider will be signed.
	// When true authentication requests sent to the identity provider will be signed.
	SignRequest *bool `json:"signRequest,omitempty" tf:"sign_request,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	TenantConfiguration []SAMLV2TenantConfigurationObservation `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the email_claim will be used when linking user.
	// The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the emailClaim will be used when linking user.
	UniqueIDClaim *string `json:"uniqueIdClaim,omitempty" tf:"unique_id_claim,omitempty"`

	// Whether or not FusionAuth will use the NameID element value as the email address of the user for reconciliation processing. If this is false, then the email_claim property must be set.
	// Whether or not FusionAuth will use the NameID element value as the email address of the user for reconciliation processing. If this is false, then the `email_claim` property must be set.
	UseNameForEmail *bool `json:"useNameForEmail,omitempty" tf:"use_name_for_email,omitempty"`

	// The name of the claim in the SAML response that FusionAuth uses to identify the username. If this is not set, the NameId value will be used to link a user. This property is required when linkingStrategy is set to LinkByUsername or LinkByUsernameForExistingUser.
	// The name of the claim in the SAML response that FusionAuth uses to identify the username. If this is not set, the NameId value will be used to link a user. This property is required when linkingStrategy is set to LinkByUsername or LinkByUsernameForExistingUser.
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`

	// The Ids of the keys stored in Key Master that are used to verify the SAML response sent back to FusionAuth from the identity provider. These keys must be verification only keys or certificates (meaning that they only have a public key component). The first entry is the default verification key and is the value FusionAuth reports back in key_id. Exactly one of key_id or verification_key_ids must be set. Requires FusionAuth 1.69.0 or later.
	// The Ids of the keys stored in Key Master that are used to verify the SAML response sent back to FusionAuth from the identity provider. These keys must be verification only keys or certificates (meaning that they only have a public key component). The first entry is the default verification key. Requires FusionAuth 1.69.0 or later.
	VerificationKeyIds []*string `json:"verificationKeyIds,omitempty" tf:"verification_key_ids,omitempty"`

	// The XML signature canonicalization method used when digesting and signing the SAML request.
	// The XML signature canonicalization method used when digesting and signing the SAML request.
	XMLSignatureCanonicalizationMethod *string `json:"xmlSignatureCanonicalizationMethod,omitempty" tf:"xml_signature_canonicalization_method,omitempty"`
}

type SAMLV2Parameters struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	// +kubebuilder:validation:Optional
	ApplicationConfiguration []SAMLV2ApplicationConfigurationParameters `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// The configuration for the SAML assertion.
	// The assertion configuration for the SAML v2 identity provider.
	// +kubebuilder:validation:Optional
	AssertionConfiguration []AssertionConfigurationParameters `json:"assertionConfiguration,omitempty" tf:"assertion_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// This is an optional Application specific override for the top level button image URL.
	// The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
	// +kubebuilder:validation:Optional
	ButtonImageURL *string `json:"buttonImageUrl,omitempty" tf:"button_image_url,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// +kubebuilder:validation:Optional
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
	// +kubebuilder:validation:Optional
	// +listType=set
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// The name of the email claim (Attribute in the Assertion element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the use_name_for_email flag must be true.
	// The name of the email claim (Attribute in the Assertion element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the `use_name_for_email` flag must be true.
	// +kubebuilder:validation:Optional
	EmailClaim *string `json:"emailClaim,omitempty" tf:"email_claim,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The SAML v2 login page of the identity provider.
	// The SAML v2 login page of the identity provider.
	// +kubebuilder:validation:Optional
	IdpEndpoint *string `json:"idpEndpoint,omitempty" tf:"idp_endpoint,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The configuration for the IdP initiated login.
	// The configuration for the IdP initiated login.
	// +kubebuilder:validation:Optional
	IdpInitiatedConfiguration []IdpInitiatedConfigurationParameters `json:"idpInitiatedConfiguration,omitempty" tf:"idp_initiated_configuration,omitempty"`

	// The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Required when enabled is true.
	// The EntityId (unique identifier) FusionAuth uses as the SAML service provider. FusionAuth expects the Audience value in the SAML assertion to match this value. When not provided, FusionAuth uses the default service provider EntityId of `<base_url>/samlv2/sp/<identityProviderId>`; that default is applied when serving metadata and validating assertions and is not stored on the identity provider, so this attribute stays empty until you set it explicitly. This value is not required to be a URI, but it must not be an empty string when provided.
	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component). In version 1.69.0 and above, use verification_key_ids instead. This field will continue to be populated with the first entry in verification_key_ids for backward compatibility, so removing it from your configuration no longer clears it. Set verification_key_ids instead. Exactly one of key_id or verification_key_ids must be set. See the 1.69.0 Key Configuration Migration Guide.
	// The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Key
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Reference to a Key in fusionauth to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDRef *v2.NamespacedReference `json:"keyIdRef,omitempty" tf:"-"`

	// Selector for a Key in fusionauth to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDSelector *v2.NamespacedSelector `json:"keyIdSelector,omitempty" tf:"-"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Lambda
	// +kubebuilder:validation:Optional
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// Reference to a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDRef *v2.NamespacedReference `json:"lambdaReconcileIdRef,omitempty" tf:"-"`

	// Selector for a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDSelector *v2.NamespacedSelector `json:"lambdaReconcileIdSelector,omitempty" tf:"-"`

	// The linking strategy to use when creating the link between the SAML v2 Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the SAML v2 Identity Provider and the user.
	// +kubebuilder:validation:Optional
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The configuration for the login hint.
	// The configuration for the login hint.
	// +kubebuilder:validation:Optional
	LoginHintConfiguration []LoginHintConfigurationParameters `json:"loginHintConfiguration,omitempty" tf:"login_hint_configuration,omitempty"`

	// The name of this OpenID Connect identity provider. This is only used for display purposes.
	// The name of the provider. This is only used for display purposes.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response. When this parameter is omitted a default value of urn:oasis:names:tc:SAML:2.0:nameid-format:persistent will be used.
	// The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response. When this parameter is omitted a default value of urn:oasis:names:tc:SAML:2.0:nameid-format:persistent will be used.
	// +kubebuilder:validation:Optional
	NameIDFormat *string `json:"nameIdFormat,omitempty" tf:"name_id_format,omitempty"`

	// When true the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
	// When true the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
	// +kubebuilder:validation:Optional
	PostRequest *bool `json:"postRequest,omitempty" tf:"post_request,omitempty"`

	// The key pair Id to use to sign the SAML request. Required when sign_request is true.
	// The key pair Id to use to sign the SAML request. Required when `sign_request` is true.
	// +kubebuilder:validation:Optional
	RequestSigningKey *string `json:"requestSigningKey,omitempty" tf:"request_signing_key,omitempty"`

	// When true authentication requests sent to the identity provider will be signed.
	// When true authentication requests sent to the identity provider will be signed.
	// +kubebuilder:validation:Optional
	SignRequest *bool `json:"signRequest,omitempty" tf:"sign_request,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// +kubebuilder:validation:Optional
	TenantConfiguration []SAMLV2TenantConfigurationParameters `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`

	// The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the email_claim will be used when linking user.
	// The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the emailClaim will be used when linking user.
	// +kubebuilder:validation:Optional
	UniqueIDClaim *string `json:"uniqueIdClaim,omitempty" tf:"unique_id_claim,omitempty"`

	// Whether or not FusionAuth will use the NameID element value as the email address of the user for reconciliation processing. If this is false, then the email_claim property must be set.
	// Whether or not FusionAuth will use the NameID element value as the email address of the user for reconciliation processing. If this is false, then the `email_claim` property must be set.
	// +kubebuilder:validation:Optional
	UseNameForEmail *bool `json:"useNameForEmail,omitempty" tf:"use_name_for_email,omitempty"`

	// The name of the claim in the SAML response that FusionAuth uses to identify the username. If this is not set, the NameId value will be used to link a user. This property is required when linkingStrategy is set to LinkByUsername or LinkByUsernameForExistingUser.
	// The name of the claim in the SAML response that FusionAuth uses to identify the username. If this is not set, the NameId value will be used to link a user. This property is required when linkingStrategy is set to LinkByUsername or LinkByUsernameForExistingUser.
	// +kubebuilder:validation:Optional
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`

	// The Ids of the keys stored in Key Master that are used to verify the SAML response sent back to FusionAuth from the identity provider. These keys must be verification only keys or certificates (meaning that they only have a public key component). The first entry is the default verification key and is the value FusionAuth reports back in key_id. Exactly one of key_id or verification_key_ids must be set. Requires FusionAuth 1.69.0 or later.
	// The Ids of the keys stored in Key Master that are used to verify the SAML response sent back to FusionAuth from the identity provider. These keys must be verification only keys or certificates (meaning that they only have a public key component). The first entry is the default verification key. Requires FusionAuth 1.69.0 or later.
	// +kubebuilder:validation:Optional
	VerificationKeyIds []*string `json:"verificationKeyIds,omitempty" tf:"verification_key_ids,omitempty"`

	// The XML signature canonicalization method used when digesting and signing the SAML request.
	// The XML signature canonicalization method used when digesting and signing the SAML request.
	// +kubebuilder:validation:Optional
	XMLSignatureCanonicalizationMethod *string `json:"xmlSignatureCanonicalizationMethod,omitempty" tf:"xml_signature_canonicalization_method,omitempty"`
}

type SAMLV2TenantConfigurationInitParameters struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type SAMLV2TenantConfigurationObservation struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type SAMLV2TenantConfigurationParameters struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	// +kubebuilder:validation:Optional
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// +kubebuilder:validation:Optional
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/namespaced/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.NamespacedReference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.NamespacedSelector `json:"tenantIdSelector,omitempty" tf:"-"`
}

// SAMLV2Spec defines the desired state of SAMLV2
type SAMLV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SAMLV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SAMLV2InitParameters `json:"initProvider,omitempty"`
}

// SAMLV2Status defines the observed state of SAMLV2.
type SAMLV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SAMLV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SAMLV2 is the Schema for the SAMLV2s API. SAML v2 Identity Provider Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,fusionauth}
type SAMLV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.buttonText) || (has(self.initProvider) && has(self.initProvider.buttonText))",message="spec.forProvider.buttonText is a required parameter"
	Spec   SAMLV2Spec   `json:"spec"`
	Status SAMLV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SAMLV2List contains a list of SAMLV2s
type SAMLV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SAMLV2 `json:"items"`
}

// Repository type metadata.
var (
	SAMLV2_Kind             = "SAMLV2"
	SAMLV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SAMLV2_Kind}.String()
	SAMLV2_KindAPIVersion   = SAMLV2_Kind + "." + CRDGroupVersion.String()
	SAMLV2_GroupVersionKind = CRDGroupVersion.WithKind(SAMLV2_Kind)
)

func init() {
	SchemeBuilder.Register(&SAMLV2{}, &SAMLV2List{})
}
