// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TwitchApplicationConfigurationInitParameters struct {

	// ID of the Application to apply this configuration to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Application
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.Reference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.Selector `json:"applicationIdSelector,omitempty" tf:"-"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// The top-level Xbox client id for your Application. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// This is an optional Application specific override for the top level client_id.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The top-level client secret to use with the Xbox Identity Provider when retrieving the long-lived token. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// This is an optional Application specific override for the top level client_secret.
	ClientSecretSecretRef *v2.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// This is an optional Application specific override for the top level scope.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TwitchApplicationConfigurationObservation struct {

	// ID of the Application to apply this configuration to.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// The top-level Xbox client id for your Application. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// This is an optional Application specific override for the top level client_id.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// This is an optional Application specific override for the top level scope.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TwitchApplicationConfigurationParameters struct {

	// ID of the Application to apply this configuration to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Application
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v2.Reference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in fusionauth to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v2.Selector `json:"applicationIdSelector,omitempty" tf:"-"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// This is an optional Application specific override for the top level button text.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// The top-level Xbox client id for your Application. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// This is an optional Application specific override for the top level client_id.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The top-level client secret to use with the Xbox Identity Provider when retrieving the long-lived token. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// This is an optional Application specific override for the top level client_secret.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v2.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// Determines if a UserRegistration is created for the User automatically or not. If a user doesn’t exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.
	// +kubebuilder:validation:Optional
	CreateRegistration *bool `json:"createRegistration,omitempty" tf:"create_registration,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// This is an optional Application specific override for the top level scope.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TwitchInitParameters struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	ApplicationConfiguration []TwitchApplicationConfigurationInitParameters `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// The top-level Xbox client id for your Application. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// The top-level Twitch client id for your Application. This value is retrieved from the Twitch developer website when you setup your Twitch developer account.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The top-level client secret to use with the Xbox Identity Provider when retrieving the long-lived token. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// The top-level client secret to use with the Twitch Identity Provider when retrieving the long-lived token. This value is retrieved from the Twitch developer website when you setup your Twitch developer account.
	ClientSecretSecretRef v2.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Lambda
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// Reference to a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDRef *v2.Reference `json:"lambdaReconcileIdRef,omitempty" tf:"-"`

	// Selector for a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDSelector *v2.Selector `json:"lambdaReconcileIdSelector,omitempty" tf:"-"`

	// The linking strategy to use when creating the link between the Twitch Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the Twitch Identity Provider and the user.
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The name of the provider. This is only used for display purposes. The display name of this provider instance. Required when using a provided tenant_id or identity_provider.tenant_id.
	// The name of the provider. This is only used for display purposes.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// The top-level scope that you are requesting from Twitch.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	TenantConfiguration []TwitchTenantConfigurationInitParameters `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.Reference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.Selector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type TwitchObservation struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	ApplicationConfiguration []TwitchApplicationConfigurationObservation `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// The top-level Xbox client id for your Application. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// The top-level Twitch client id for your Application. This value is retrieved from the Twitch developer website when you setup your Twitch developer account.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// The linking strategy to use when creating the link between the Twitch Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the Twitch Identity Provider and the user.
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The name of the provider. This is only used for display purposes. The display name of this provider instance. Required when using a provided tenant_id or identity_provider.tenant_id.
	// The name of the provider. This is only used for display purposes.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// The top-level scope that you are requesting from Twitch.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	TenantConfiguration []TwitchTenantConfigurationObservation `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type TwitchParameters struct {

	// The configuration for each Application that the identity provider is enabled for.
	// The configuration for each Application that the identity provider is enabled for.
	// +kubebuilder:validation:Optional
	ApplicationConfiguration []TwitchApplicationConfigurationParameters `json:"applicationConfiguration,omitempty" tf:"application_configuration,omitempty"`

	// A map of attribute mappings applied during user reconciliation when a reconcile Lambda is not configured. Each key is the FusionAuth target field path and must begin with user. or registration.. Each value is the source expression in the identity provider response payload. A dot-notated value such as email or id_token.given_name is converted to a JSON Pointer. A value that starts with / is treated as a JSON Pointer as-is. This property cannot be used with identityProvider.lambdaConfiguration.reconcileId. This property is ignored when identityProvider.linkingStrategy is LinkAnonymously. This property defaults to an empty map. Mappings that resolve to null, cannot be extracted, or cannot be written to the target field are ignored. Mappings to user.password do not set a password.
	// A map of Identity Provider claim or response values to FusionAuth user attributes or registration fields.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// The top-level button text to use on the FusionAuth login page for this Identity Provider.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// The top-level Xbox client id for your Application. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// The top-level Twitch client id for your Application. This value is retrieved from the Twitch developer website when you setup your Twitch developer account.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The top-level client secret to use with the Xbox Identity Provider when retrieving the long-lived token. This value is retrieved from the Xbox developer website when you setup your Xbox developer account.
	// The top-level client secret to use with the Twitch Identity Provider when retrieving the long-lived token. This value is retrieved from the Twitch developer website when you setup your Twitch developer account.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef v2.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
	// +kubebuilder:validation:Optional
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// Determines if this identity provider is enabled for the Application specified by the applicationId key.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// The ID to use for the new identity provider. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	IdpID *string `json:"idpId,omitempty" tf:"idp_id,omitempty"`

	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Lambda
	// +kubebuilder:validation:Optional
	LambdaReconcileID *string `json:"lambdaReconcileId,omitempty" tf:"lambda_reconcile_id,omitempty"`

	// Reference to a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDRef *v2.Reference `json:"lambdaReconcileIdRef,omitempty" tf:"-"`

	// Selector for a Lambda in fusionauth to populate lambdaReconcileId.
	// +kubebuilder:validation:Optional
	LambdaReconcileIDSelector *v2.Selector `json:"lambdaReconcileIdSelector,omitempty" tf:"-"`

	// The linking strategy to use when creating the link between the Twitch Identity Provider and the user. To change the linking strategy for an enabled identity provider, disable the provider, make your change, then re-enable the provider.
	// The linking strategy to use when creating the link between the Twitch Identity Provider and the user.
	// +kubebuilder:validation:Optional
	LinkingStrategy *string `json:"linkingStrategy,omitempty" tf:"linking_strategy,omitempty"`

	// The name of the provider. This is only used for display purposes. The display name of this provider instance. Required when using a provided tenant_id or identity_provider.tenant_id.
	// The name of the provider. This is only used for display purposes.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// This is an optional Application specific override for the top level scope.
	// The top-level scope that you are requesting from Twitch.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// The source of this Identity Provider. The maximum length is 191 characters. This value is only used on create. If updated, a new Identity Provider will be created.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// The configuration for each Tenant that limits the number of links a user may have for a particular identity provider.
	// +kubebuilder:validation:Optional
	TenantConfiguration []TwitchTenantConfigurationParameters `json:"tenantConfiguration,omitempty" tf:"tenant_configuration,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// The unique Id of the Tenant. Providing a value creates an identity provider scoped to the specified tenant, otherwise a global identity provider is created. Tenant-scoped identity providers can only be used to authenticate in the context of the specified tenant. Global identity providers can be used with any tenant. This value cannot be updated after creation and requires recreating the resource to change.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.Reference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.Selector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type TwitchTenantConfigurationInitParameters struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.Reference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.Selector `json:"tenantIdSelector,omitempty" tf:"-"`
}

type TwitchTenantConfigurationObservation struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type TwitchTenantConfigurationParameters struct {

	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks.
	// When enabled, the number of identity provider links a user may create is enforced by maximumLinks
	// +kubebuilder:validation:Optional
	LimitUserLinkCountEnabled *bool `json:"limitUserLinkCountEnabled,omitempty" tf:"limit_user_link_count_enabled,omitempty"`

	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// Determines if this provider is enabled. If it is false then it will be disabled globally.
	// +kubebuilder:validation:Optional
	LimitUserLinkCountMaximumLinks *int64 `json:"limitUserLinkCountMaximumLinks,omitempty" tf:"limit_user_link_count_maximum_links,omitempty"`

	// The unique Id of the tenant that this configuration applies to.
	// +crossplane:generate:reference:type=github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1.Tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Reference to a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDRef *v2.Reference `json:"tenantIdRef,omitempty" tf:"-"`

	// Selector for a Tenant in fusionauth to populate tenantId.
	// +kubebuilder:validation:Optional
	TenantIDSelector *v2.Selector `json:"tenantIdSelector,omitempty" tf:"-"`
}

// TwitchSpec defines the desired state of Twitch
type TwitchSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TwitchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TwitchInitParameters `json:"initProvider,omitempty"`
}

// TwitchStatus defines the observed state of Twitch.
type TwitchStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TwitchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Twitch is the Schema for the Twitchs API. Twitch Identity Provider Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,fusionauth}
type Twitch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.buttonText) || (has(self.initProvider) && has(self.initProvider.buttonText))",message="spec.forProvider.buttonText is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientSecretSecretRef)",message="spec.forProvider.clientSecretSecretRef is a required parameter"
	Spec   TwitchSpec   `json:"spec"`
	Status TwitchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TwitchList contains a list of Twitchs
type TwitchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Twitch `json:"items"`
}

// Repository type metadata.
var (
	Twitch_Kind             = "Twitch"
	Twitch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Twitch_Kind}.String()
	Twitch_KindAPIVersion   = Twitch_Kind + "." + CRDGroupVersion.String()
	Twitch_GroupVersionKind = CRDGroupVersion.WithKind(Twitch_Kind)
)

func init() {
	SchemeBuilder.Register(&Twitch{}, &TwitchList{})
}
