// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MessengerInitParameters struct {

	// The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	AccountSid *string `json:"accountSid,omitempty" tf:"account_sid,omitempty"`

	// The Twilio Auth Token to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// The Twilio Auth Token to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	AuthTokenSecretRef *v2.SecretKeySelector `json:"authTokenSecretRef,omitempty" tf:"-"`

	// A JSON string that can hold any information about the Twilio Messenger that should be persisted. Must be a JSON string.
	// An object that can hold any information about the Twilio Messenger that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// If debug is enabled, an event log is created to assist in debugging messenger errors. Defaults to false.
	// If debug is enabled, an event log is created to assist in debugging messenger errors.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.
	// The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.
	FromPhoneNumber *string `json:"fromPhoneNumber,omitempty" tf:"from_phone_number,omitempty"`

	// The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard. If this is set, the fromPhoneNumber will be ignored.
	// The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard. If this is set, the fromPhoneNumber will be ignored.
	MessagingServiceSid *string `json:"messagingServiceSid,omitempty" tf:"messaging_service_sid,omitempty"`

	// The Id to use for the new Messenger. If not specified a secure random UUID will be generated.
	// The Id to use for the new Messenger. If not specified a secure random UUID will be generated.
	MessengerID *string `json:"messengerId,omitempty" tf:"messenger_id,omitempty"`

	// The unique Messenger name.
	// The unique Messenger name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Twilio URL that FusionAuth will use to communicate with the Twilio API.
	// The Twilio URL that FusionAuth will use to communicate with the Twilio API.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type MessengerObservation struct {

	// The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	AccountSid *string `json:"accountSid,omitempty" tf:"account_sid,omitempty"`

	// A JSON string that can hold any information about the Twilio Messenger that should be persisted. Must be a JSON string.
	// An object that can hold any information about the Twilio Messenger that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// If debug is enabled, an event log is created to assist in debugging messenger errors. Defaults to false.
	// If debug is enabled, an event log is created to assist in debugging messenger errors.
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.
	// The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.
	FromPhoneNumber *string `json:"fromPhoneNumber,omitempty" tf:"from_phone_number,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard. If this is set, the fromPhoneNumber will be ignored.
	// The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard. If this is set, the fromPhoneNumber will be ignored.
	MessagingServiceSid *string `json:"messagingServiceSid,omitempty" tf:"messaging_service_sid,omitempty"`

	// The Id to use for the new Messenger. If not specified a secure random UUID will be generated.
	// The Id to use for the new Messenger. If not specified a secure random UUID will be generated.
	MessengerID *string `json:"messengerId,omitempty" tf:"messenger_id,omitempty"`

	// The unique Messenger name.
	// The unique Messenger name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Twilio URL that FusionAuth will use to communicate with the Twilio API.
	// The Twilio URL that FusionAuth will use to communicate with the Twilio API.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type MessengerParameters struct {

	// The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// +kubebuilder:validation:Optional
	AccountSid *string `json:"accountSid,omitempty" tf:"account_sid,omitempty"`

	// The Twilio Auth Token to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// The Twilio Auth Token to use when connecting to the Twilio API. This can be found in your Twilio dashboard.
	// +kubebuilder:validation:Optional
	AuthTokenSecretRef *v2.SecretKeySelector `json:"authTokenSecretRef,omitempty" tf:"-"`

	// A JSON string that can hold any information about the Twilio Messenger that should be persisted. Must be a JSON string.
	// An object that can hold any information about the Twilio Messenger that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema. Must be a JSON string.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// If debug is enabled, an event log is created to assist in debugging messenger errors. Defaults to false.
	// If debug is enabled, an event log is created to assist in debugging messenger errors.
	// +kubebuilder:validation:Optional
	Debug *bool `json:"debug,omitempty" tf:"debug,omitempty"`

	// The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.
	// The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.
	// +kubebuilder:validation:Optional
	FromPhoneNumber *string `json:"fromPhoneNumber,omitempty" tf:"from_phone_number,omitempty"`

	// The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard. If this is set, the fromPhoneNumber will be ignored.
	// The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard. If this is set, the fromPhoneNumber will be ignored.
	// +kubebuilder:validation:Optional
	MessagingServiceSid *string `json:"messagingServiceSid,omitempty" tf:"messaging_service_sid,omitempty"`

	// The Id to use for the new Messenger. If not specified a secure random UUID will be generated.
	// The Id to use for the new Messenger. If not specified a secure random UUID will be generated.
	// +kubebuilder:validation:Optional
	MessengerID *string `json:"messengerId,omitempty" tf:"messenger_id,omitempty"`

	// The unique Messenger name.
	// The unique Messenger name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Twilio URL that FusionAuth will use to communicate with the Twilio API.
	// The Twilio URL that FusionAuth will use to communicate with the Twilio API.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// MessengerSpec defines the desired state of Messenger
type MessengerSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   MessengerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MessengerInitParameters `json:"initProvider,omitempty"`
}

// MessengerStatus defines the observed state of Messenger.
type MessengerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MessengerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Messenger is the Schema for the Messengers API. Twilio Messenger Resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,fusionauth}
type Messenger struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountSid) || (has(self.initProvider) && has(self.initProvider.accountSid))",message="spec.forProvider.accountSid is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   MessengerSpec   `json:"spec"`
	Status MessengerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MessengerList contains a list of Messengers
type MessengerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Messenger `json:"items"`
}

// Repository type metadata.
var (
	Messenger_Kind             = "Messenger"
	Messenger_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Messenger_Kind}.String()
	Messenger_KindAPIVersion   = Messenger_Kind + "." + CRDGroupVersion.String()
	Messenger_GroupVersionKind = CRDGroupVersion.WithKind(Messenger_Kind)
)

func init() {
	SchemeBuilder.Register(&Messenger{}, &MessengerList{})
}
