// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/lansweeper-oss/provider-fusionauth/apis/cluster/fusionauth/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Field.
func (mg *Field) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConsentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ConsentIDRef,
		Selector:     mg.Spec.ForProvider.ConsentIDSelector,
		To: reference.To{
			List:    &v1alpha1.ConsentList{},
			Managed: &v1alpha1.Consent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConsentID")
	}
	mg.Spec.ForProvider.ConsentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConsentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConsentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ConsentIDRef,
		Selector:     mg.Spec.InitProvider.ConsentIDSelector,
		To: reference.To{
			List:    &v1alpha1.ConsentList{},
			Managed: &v1alpha1.Consent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConsentID")
	}
	mg.Spec.InitProvider.ConsentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConsentIDRef = rsp.ResolvedReference

	return nil
}
